### ISSUE TITLE
cpp.py : missing return in t_CPP_COMMENT2() ?

### ISSUE THREAD

**Issue by gryken2014** [dabeaz/ply#103]
Hi, 

I've noticed, in  the cpp.py, example file :
- The function t_CPP_COMMENT1() is ending with return t.
- But the function t_CPP_COMMENT2() doesn't .

Is-this a real problem,or not ?

Thanks

**Comment by RomaVis** [comment]
Hi,

Due to missing return, CPP_COMMENT2 tokens are simply discarded (seems they should be replaced by CPP_WS). Also lineno should be tracked in t_CPP_COMMENT2(). The proposal is to rewrite function the following way:

```
def t_CPP_COMMENT2(t):
    r'(//.*?(\n|$))'
    t.lexer.lineno += 1
    # replace with '\n'
    t.type = 'CPP_WS'; t.value = '\n'
    return t
```

**Comment by dabeaz** [comment]
The preprocessor module isn't actually used for anything in PLY proper.  Still fixed this.
