### ISSUE TITLE
Support FIPS

### ISSUE THREAD

**Issue by stlaz** [dabeaz/ply#105]
Hello,
yacc.py currently uses md5 to get the signature of a grammar. md5 however is not supported in FIPS. I proposed to change md5 for sha256 in PR https://github.com/dabeaz/ply/pull/104 but feel free to use other system to get grammar signature that's FIPS-compatible.

**Comment by dabeaz** [comment]
PLY contains no cryptographic functionality.

**Comment by stlaz** [comment]
Please reopen the issue, then, as it reaises and problems in FIPS-enabled systems. If you do not contain cryptographic functionality you should not use cryptographic functions.

**Comment by lorengordon** [comment]
fwiw, i just tested FIPS-mode with ply 3.10 and this is working now. it was broken under ply 3.9 and earlier.

**Comment by stlaz** [comment]
@lorengordon Yes, @dabeaz tries to explain that there was a change in 3.10 in https://github.com/dabeaz/ply/issues/106 but thanks for caring :)

**Comment by lorengordon** [comment]
Ahh, good deal. I was searching for FIPS so missed that issue.
