### ISSUE TITLE
[Bug] Remove cryptographic functions

### ISSUE THREAD

**Issue by stlaz** [dabeaz/ply#106]
Hello,
The hashlib.md5 used for getting digest at https://github.com/dabeaz/ply/blob/master/ply/yacc.py#L2974 breaks projects using this library if these are run in FIPS mode. Please, replace this signature acquiring with a different mechanism.

Proposal:
The cffi library was solving the same issue some 4 years ago:
https://bitbucket.org/cffi/cffi/issues/15/stamp-out-all-md5
They solved it by replacing the md5 signatures with crc32:
https://bitbucket.org/cffi/cffi/commits/d97e4436b7bd

**Comment by dabeaz** [comment]
PLY-3.10 does something different

**Comment by stlaz** [comment]
Thanks.
