### ISSUE TITLE
Can't call parser.restart() before a call to parser.input()

### ISSUE THREAD

**Issue by kpinc** [dabeaz/ply#109]
Hi,

I'm using ply and wanted to write some pytest tests.  Seemed to make sense to me to
have each test call parser.restart() before doing whatever it does.  That way I can
reuse the same parser and not have the overhead of calling yacc.yacc() repeatedly.

But if I try to call parser.restart() before doing anything, when my first test is run,
I get:
```
devel/pytest/local/lib/python2.7/site-packages/ply/yacc.py:298: in restart
    del self.statestack[:]
E   AttributeError: LRParser instance has no attribute 'statestack'
```

Should I be doing something different when writing tests or does it make sense
to allow each test to call parser.restart() before it does anything?  If nothing
else it'd be nice to have some guidance in the documentation.

Below is a sample pytest file with an ugly hack at the top that seems
to work.  There must be a better way.

----------<snip>-----------
```
# An example test_rules_yacc.py file
from myprogram import rules_yacc


# Global parser
parser = rules_yacc.parser

# Start the parser running so that we can reset it before each test.  (!)
try:
    parser.parse('')
except Exception:
    pass
finally:
    parser.restart()

# Tests

def test_string():
    '''A simple string works.'''
    parser.restart()
    assert parser.parse('two words') == [('string', 'two words')]
```

**Comment by dabeaz** [comment]
restart() is only for use during parser error-recovery.  It is not something that would ever be called on its own outside of parsing.   If you want to parse different things with the same parser, call `parse()` over again with different inputs.
