### ISSUE TITLE
decorator @TOKEN inside module

### ISSUE THREAD

**Issue by hansbonini** [dabeaz/ply#115]
Hi all,
When i tried to create a class module, to use inside Lex. Lex don't recognize the TOKEN decorator and the following message is received on console: "NameError: name 'TOKEN' is not defined"

Example:

```python
# parent.py
import ply.lex as lex
import ply.yacc as yacc
from modules import newmodule

if __name__ == "__main__":
 init = lex.lex(module=newmodule)
```
and 

```python
# module.py
class Lexer (object):
 tokens = []
 @TOKEN(r'[\n|\r\n]+')
 def t_newline(self, t):
  t.lexer.lineno += len(t.value)

 def t_error(self, t):
  print("Illegal character '%s'" % t.value[0])
  t.lexer.skip(1)

 def __init__(self):
  pass
```
Anybody can help me? I don't want to use doctstrings for rules.

**Comment by dabeaz** [comment]
TOKEN is a something that would have to be imported:

    from ply.lex import TOKEN

**Comment by hansbonini** [comment]
Thank you!
