### ISSUE TITLE
How can I generate tokens depending on indentation?

### ISSUE THREAD

**Issue by asherbar** [dabeaz/ply#117]
Say I'd like to compile a Python-like language which takes into account indentation. So, for example, I'd like to define a simple function statement as following:

```
def p_func_stmt(p):
    """
    func_stmt : DEF_KEYWORD ID COLON NEWLINE INDENT stmts DETENT
    """
    # handle function definition here
```

How would I define the `INDENT` and `DEDENT` tokens?

Thank you.

**Comment by dabeaz** [comment]
Might look at the example/GardenSnake code for some ideas on this.

**Comment by asherbar** [comment]
Looks exactly like what I was looking for. Thank you.
