### ISSUE TITLE
Unable to parse seemingly good input

### ISSUE THREAD

**Issue by mikeyupol** [dabeaz/ply#121]
Hi Everyone,

Please consider the following self contained program:

```
#!/usr/bin/python
import ply.yacc as yacc
import ply.lex as lex

tokens = ('N','D','I')

t_N = r'N'
t_D = r'D'
t_I = r'I'
t_ignore = r' '

def t_error(e):
    pass

start = 'C'

def p_C(p):
    """ C : N Cbody D I """
    print "C"

def p_Cbody(p):
    """ Cbody : I Cbody
              | D Cbody
              |
    """
    print "Cbody"

def p_error(p):
    print "ERROR:",p

print "Version:",yacc.__version__
lexer = lex.lex()
parser = yacc.yacc(debug=False,write_tables=False)
parser.parse('N I D I')
````

Unless I'm not understanding it correctly, the input string "N I D I" should be easily parsed by the above grammar. However ply gives me EOF error:

````
Version: 3.7
ERROR: None
````

Does anybody know what is going on here?  I'm using python 2.7.12. I've tried ply 3.10 with the same result.

Thanks.
-Mike

**Comment by mikeyupol** [comment]
I'm not sure why git code fragment can't parse double underscore around "version" above. It should have been "yacc.__version__".

**Comment by mikeyupol** [comment]
Sorry, this is my first time posting to github, I didn't anticipate that code fragments would look so awful here.

**Comment by kirbyfan64** [comment]
You're supposed to surround multi-line code fragments with triple backticks:

https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by mikeyupol** [comment]
Thank you, I edited my original post. I though that "Insert code" (<>) button would do that for me, but for some reason it surrounds with just one back tick.

**Comment by dabeaz** [comment]
The grammar has 3 shift/reduce conflicts in it.   The "Cbody' rule is written such that it will parse any arbitrary sequence of {D, I} tokens into a "Cbody".  As a result, the end of that input string 'N I D I' is getting pulled inside Cbody and then it's barfing on an unexpected EOF.   I'm not sure that this can be parsed by PLY given that it only looks one token ahead while parsing. 

Note: Debugging tricky parsing problems is often helped by looking at the 'parser.out' file created by PLY.

**Comment by mikeyupol** [comment]
Thank you for getting back. Initially I thought that LALR parser can handle any unambiguous grammar for a context free language, but now I see that is not the case. I've reduced the above to a minimum unparsable example, with grammar:

```
C : Cbody I
Cbody : Cbody | <empty>
```
and input "I I". This also fails with EOF. I think these shift/reduce conflicts are similar to the classic if/else ambiguity in LALR grammars, where "else" goes with the outermost "if".

A solution then, if I still want to use LALR(1) parser, would be to rewrite my grammar to remove the shift/reduce conflicts. The above "N I D I" example is part of a larger grammar, and it becomes non-trivial to change it in some cases (and also less readable).

Thanks!

**Comment by dabeaz** [comment]
An LALR parser can parse an unambiguous grammar, but if you're getting shift/reduce conflicts being reported, then there is definitely ambiguity somewhere (and all bets are off).    Yes, you'll have to figure out some strategy for it.  Maybe rewriting the grammar. Maybe using precedence specifiers. Maybe using some kind of insane trick to fix the parse later (sometimes you can parse it "wrong", but then detect it and unwind it into the right thing afterwards).

**Comment by mikeyupol** [comment]
According to Grune & Jacobs book, an unambiguous grammar produces exactly one parse tree for each string it accepts. As far as I can see the two grammars above are unambiguous according to that definition.  However LALR(1) parser fails on them. I think there is some notion of LALR ambiguity, which is stronger than general ambiguity, i.e. general ambiguous grammars are a proper subset of LALR ambiguous grammars.

I've tried the same examples with Flex & Bison and get the same errors.

**Comment by dabeaz** [comment]
Main concern with PLY is that it replicate behavior of Flex & Bison.  If the same results are obtained, I wouldn't classify this as a PLY bug.
