### ISSUE TITLE
Hi I am not being able create langue having functions like fun()

### ISSUE THREAD

**Issue by johirbuet** [dabeaz/ply#122]
Can you please look at this issue
https://stackoverflow.com/questions/43618740/ply-parsing-error-for-function-declaration

**Comment by kirbyfan64** [comment]
The [docs say](http://www.dabeaz.com/ply/ply.html#ply_nn6):

>To handle reserved words, you should write a single rule to match an identifier and do a special name lookup in a function like this:

```python
reserved = {
   'if' : 'IF',
   'then' : 'THEN',
   'else' : 'ELSE',
   'while' : 'WHILE',
   ...
}

tokens = ['LPAREN','RPAREN',...,'ID'] + list(reserved.values())

def t_ID(t):
    r'[a-zA-Z_][a-zA-Z_0-9]*'
    t.type = reserved.get(t.value,'ID')    # Check for reserved words
    return t
```

You're basically missing the entire second half...
