### ISSUE TITLE
Unable to build parser yacc error using python 3.5. Same program runs perfectly on python 2.7.6

### ISSUE THREAD

**Issue by hamzaaltaf** [dabeaz/ply#123]
ERROR: no rules of the form p_rulename are defined
File "main.py", line 12, in <module>
    parser = yacc.yacc()
  File "C:\Users\Hamza Altaf\AppData\Local\Programs\Python\Python35-32\lib\site-packages\ply\yacc.py", line 3317, in yacc
    raise YaccError('Unable to build parser')
ply.yacc.YaccError: Unable to build parser

**When I run the same file on python 2.7.6 it runs perfectly.**

**Comment by johnyf** [comment]
Sharing a minimal example that produces the same behavior could probably help find the cause.

**Comment by dabeaz** [comment]
I'm not aware of any problem with using PLY on Python 3.  Would need to see a concrete example that duplicates broken behavior.
