### ISSUE TITLE
t_ignore contains a literal backslash '\' ply

### ISSUE THREAD

**Issue by NetWilliam** [dabeaz/ply#126]
I want to t_ignore to ignore the white space in my input string. so I set `t_ignore` to `r"\s"`
but when I run the program I get a warning as title, I notice that ply code print space `' '` as illegal character
``` 
Illegal character ' '
```

Why does this happen? What should I do?

**Comment by NetWilliam** [comment]
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ply
>>> print ply.__version__
3.9
>>> 

source code:
```
#!/usr/bin/env python
#! encoding: utf-8

import ply.lex as lex

raw_in = u"benchPress abc 20/20/20*2*12 \n\r\
飞鸟 20;20;20*2*12 \
workout \
整 整整"

reserved = {
    ur"workout": "WORKOUT",
    ur"整": "WORKOUT",
}

tokens = (
    'NUMBER',
    'MULTIPLY',
    'SEPRATOR',
    'ADD',
    'LPARENT',
    'RPARENT',
    'MOVETAG',
    #'WHITESPACE',
)

tokens = list(tokens) + list(reserved.values())

t_MULTIPLY = ur'\*'
t_SEPRATOR = ur'[/;,，。]'
t_ADD = ur'\+'
t_LPARENT = ur'\('
t_RPARENT = ur'\)'
#t_MOVETAG = r'[\w\u4E00-\u9FA5\uF900-\uFA2D]+'
#t_MOVETAG = ur'[a-zA-Z0-9_\u4e00-\u9fa5]+'
#t_WHITESPACE = ur'\s+'
#t_ignore = r'\s+'
t_ignore = '\s'

def t_MOVETAG(t):
    #ur'(\bworkout\b|\b整\b)'
    ur'[a-zA-Z0-9_\u4e00-\u9fa5]+'
    t.type = reserved.get(t.value, 'MOVETAG')
    return t

def t_NUMBER(t):
    ur'[1-9]\d*(\.\d+)?'
    t.value = float(t.value)
    return t

def t_error(t):
    print t.type
    print "Illegal character '%s'" % t.value[0]
    t.lexer.skip(1)

def t_newline(t):
    ur'\n+'
    t.lexer.lineno += len(t.value)


def main():
    lexer = lex.lex(debug=1)
    lexer.input(raw_in)
    while True:
        token = lexer.token()
        if not token:
            print "token end here"
            break
        if type(token.value) == unicode:
            print token, token.value.encode('utf-8')
        else:
            print token

if __name__ == "__main__":
    main()

```

**Comment by dabeaz** [comment]
The `t_ignore` specifier expects a string of literal characters to be ignored, not a regex.   So it's going to be something like `t_ignore = ' \t'`.   Specifying `\s` tells it to ignore the character '\\' and the character 's'.

**Comment by NetWilliam** [comment]
yes 
`t_ignore=' \t\r\n\f\v'` is what I want

**Comment by boriel** [comment]
@NetWilliam in python regular strings`\s` is not equal to those characters!
` t_ignore` is **not** a regular expression, but a plain list of chars: so `\s` here means just `\\s` nothing else.

**Comment by NetWilliam** [comment]
@boriel  yes, I mean `\s` in regex expression has same meaning of '[ \t\r\n\f\v]' which represented in `t_ignore`

**Comment by PabloDelgadoC** [comment]
You should use `t_ignore = ' \t'` and it allow you to write any amount of spaces inside your code and when you use `yacc.yacc()` and the parser, all spaces are ommited

**Comment by ArminRmt** [comment]
t_ignore = '  \s'
watch for space befor   (\)

**Comment by ArminRmt** [comment]
t_ignore=' \t\r\n\f\v\\'
this works
