### ISSUE TITLE
Copyright question

### ISSUE THREAD

**Issue by MainTankJerry** [dabeaz/ply#133]
First of all, I want to thank you for this excellent package.
I am very new to documenting my code, so my question might be silly.
If I download the package, keep it as it is, is there anything I should add to my part of the code?
If my code is like:
```
# Author: My name
# Date: XX

import XXXXX
import plyj.parser as plyj

def main():
...
...
...

if __name__ == '__main__':
  main()
```

**Comment by dabeaz** [comment]
I'm not aware of anything specifically that needs to be done.
