### ISSUE TITLE
Parser wrapped in class always generates tables when subclassed

### ISSUE THREAD

**Issue by thelonious** [dabeaz/ply#134]
I have a generic syntax (like JSON, YAML, etc.) for representing tree structures. I created a PLY parser for this format and that is defined in a class. When I use specific schemas of this data format, I create a subclass of my PLY parser class and pass in a dictionary that maps the data format's element names to Python constructors—during the parse the base class uses this dictionary to construct Python class instances for each of the data format's elements. Every time I instantiate one of my parser subclasses, I see the "Generating LALR tables" message in the console. The parser base class and subclasses each live in their own modules. I do see separate parsetab.py's in each of my subclasses' module's folders as expected, but it seems like those are being ignored or they are not found. I see that I can use tabmodule and outputdir to control the location and name of the parsetab.py file, but the fact that the file is being created in the correct location makes me think something else it up. I'm relatively new to Python, so this may be an issue with how I've setup modules, but I'm curious if you can give me any insight in how I can troubleshoot this and/or prevent the tables from being generated every time I use my parser subclasses.

**Comment by thelonious** [comment]
Just as an update, I've rearranged my architecture to a system that has only a single lever and parser; however, I still see the "Generating LALR tables" message each time I run my script.

**Comment by dabeaz** [comment]
There are a few usual causes of getting "Generating Tables" messages repeatedly:

1.  PLY doesn't have write permission to create the table file
2. There is an already-existing table file with the same name somewhere on sys.path that is being imported instead.

**Comment by thelonious** [comment]
I see the generated parsetab.py file next to my parser class. If I delete it, it is regenerated, so PLY has write permissions.

Regarding #2, I've seen this behavior on a fresh VM that has never run PLY before.

I've started debugging a bit and I'm seeing an import error when yacc tries to load the module. So, I guess this is a sys.path issue.

**Comment by thelonious** [comment]
OK, this is fixed. I'm exporting each parsetab in the modules where they are created. I then added the tabmodule argument to yacc.yacc, using the full package name.
