### ISSUE TITLE
Optional/repeating tokens

### ISSUE THREAD

**Issue by dpdani** [dabeaz/ply#136]
Hi, I was wondering if there is a way for PLY to handle optional or repeating tokens in YACC productions.
For instance, I would like to write something like this:
```python
def p_cond(p):
    '''cond : IF expr COLON block [ELIF expr COLON block]* [ELSE COLON block]?'''
    ...
```
Is this already possible in PLY? If not, I guess this issue would become a feature request, or are there other ways in which this syntax could be implemented?

**Comment by akuzminsky** [comment]
this is possible now.

```
def p_cond(p):
    '''cond : IF expr COLON block opt_elif_list [ELSE COLON block]?'''
    ...

def p_opt_elif_list(p):
    """opt_elif_list : | elif_list"""

def p_elif_list(p):
    """elif_list : elif | elif_list elif """

def p_elif(p):
    """elif : ELIF expr COLON block"""

```

**Comment by dpdani** [comment]
Thank you! 
Much appreciated 😊
