### ISSUE TITLE
Is there a way to reset the lexer and parser's states without rebuilding instances?

### ISSUE THREAD

**Issue by hhsprings** [dabeaz/ply#137]
I am using lex/yacc of ply like this:
```python
import ply.lex as lex
import ply.yacc as yacc

class _Parser(object):
    """
    Base class for a lexer/parser that has the rules defined as methods
    """
    tokens = ()
    precedence = ()

    def __init__(self, **kw):
        # ...
        # Build the lexer and parser
        self._build_lexer()
        self._build_parser()

    def _build_lexer(self):
        self._lexer = lex.lex(
            module=self,
            debug=self.debug)

    def _build_parser(self):
        self._parser = yacc.yacc(
            module=self,
            debug=self.debug,
            debugfile=self.debugfile,
            tabmodule=self.tabmodule)

    def _parse(self, s, reset=True):
        if reset:
            self._build_lexer()
            try:
                self._parser.restart()
            except AttributeError as e:
                # "'LRParser' object has no attribute 'statestack'"
                pass
        self._parser.parse(s)
```
because it seems that constructing the lexer and parser is too heavy.

Question:
1. Is there a way to reset the lexer and parser's states without rebuilding instances?
2. Is "restart()" of the parser what I want?
3. AttributeError("'LRParser' object has no attribute 'statestack'") is a bug or not?

**Comment by dabeaz** [comment]
The restart() method may only be used in the context of panic mode parser error recovery.  It is not safe to call prior to parsing or outside of parsing. 

The parse() method of the resulting parser object should reset the internal state each time you call it.

Lexer objects keep track of a line number which is not reset each time.  You might need to manually set that back if you need to.

**Comment by speculaas** [comment]
Dear dabeaz,
Thanks for this great PLY!
Can you share how to reset line number?
Best regards

**Comment by dabeaz** [comment]
I think you can just set it as an attribute (`lineno`) on the Lexer object.

**Comment by speculaas** [comment]
Dear Dabeaz,

Surprised to see you responsed so soon and thanks!

I did just as you suggested and was able to continue my team's final project on program analysis of WHILE program.

Best regards,

**Comment by leof300** [comment]
I added a rule on lexical, to reset the lineno at the end of the file:

```
def t_eof(t):
    t.lexer.lineno = 1
```
