### ISSUE TITLE
Deriving Base Parser and adding/overiding a rule in the child 

### ISSUE THREAD

**Issue by jayanthjaiswal** [dabeaz/ply#138]
I have 2 different Grammar specification, which differ slighlty so I have created a base parser for common grammer specification here [AtfBaseParser] like this:

https://github.com/jayanthjaiswal/pyoracc/blob/feature/modular/pyoracc/atf/common/atfbaseyacc.py

Now, I am deriving the base parser into two child parsers like these:

1. https://github.com/jayanthjaiswal/pyoracc/blob/feature/modular/pyoracc/atf/cdli/atfyacc.py
2.  https://github.com/jayanthjaiswal/pyoracc/blob/feature/modular/pyoracc/atf/oracc/atfyacc.py

However, the 1st derived parser does not work, where there is an overwritten rule while the 2nd one derived parser works, when there is no overwritten rule.

Yacc complains that there is only a single rule, when derived class rule overwrites base class rule instead of identifying the whole grammer rule set.

For example, the following derived class works as it does not override any rule:

```
from pyoracc.atf.common.atfbaseyacc import AtfBaseParser
from pyoracc.model.text import Text
from ply import yacc as yacc


class AtfCDLIParser(AtfBaseParser):

    tokens = AtfBaseParser.tokens
    precedence = AtfBaseParser.precedence

    def __init__(self, tabmodule='pyoracc.atf.parsetab'):
        super(AtfCDLIParser, self).__init__(tabmodule, self)
        self.parser = yacc.yacc(module=self, tabmodule=tabmodule)
```

But overriding any one rule say p_codeline in the derived class breaks the parser i.e. updating the above class like this:

```
from pyoracc.atf.common.atfbaseyacc import AtfBaseParser
from pyoracc.model.text import Text
from ply import yacc as yacc


class AtfCDLIParser(AtfBaseParser):

    tokens = AtfBaseParser.tokens
    precedence = AtfBaseParser.precedence

    def __init__(self, tabmodule='pyoracc.atf.parsetab'):
        super(AtfCDLIParser, self).__init__(tabmodule, self)
        self.parser = yacc.yacc(module=self, tabmodule=tabmodule)

    def p_codeline(self, p):
        "text_statement : AMPERSAND ID EQUALS ID newline"
        p[0] = Text()
        p[0].code = p[2]
        p[0].description = p[4]
```

I am trying to make my code modular and remove redundant rule specifications into a base class parser. Hence, this is important for our project and your reply will be really helpful.

Thanks again,
Jayanth

link to project : https://github.com/jayanthjaiswal/pyoracc/

**Comment by dabeaz** [comment]
So far as I know, inheritance has never been well supported in PLY.  You might be able to fix it with a "start" specification that points to the top-level grammar rule, but no guarantees.

**Comment by nikitagupta55** [comment]
@jayanthjaiswal  please help in resolving this issue: https://github.com/dabeaz/ply/issues/149
