### ISSUE TITLE
Ply crashing and always ends with up same error

### ISSUE THREAD

**Issue by johnlloydcruz** [dabeaz/ply#144]
I tried using it on the calc.py example, but still not working.

[https://gist.github.com/johnlloydcruz/d19a848ca4bc8dccc25a63fdf489597f](url)

Error
https://gist.github.com/johnlloydcruz/05e54fdfa05f3701529644731ca7cf92

**Comment by dabeaz** [comment]
The traceback message in the error is truncated and incomplete.  No idea.
