### ISSUE TITLE
How can I share parser between compiler and editor? need different actions

### ISSUE THREAD

**Issue by ponyatov** [dabeaz/ply#146]
Let's take some simple script (calculator for example).
Language has some grammar and we write parser module can process it.

Next, we have two separate programs:
1) _compiler_ runs in batch mode (from Makefile or direct run like `python /compiler.py sample.source`)
2) _GUI editor_ in which we want **syntax coloring**

How can I share (redefine) actions in parser (imported as module) for every program?

**Comment by kirbyfan64** [comment]
...you just import the same parser module? Not really sure what the problem is here...

**Comment by kirbyfan64** [comment]
Oh wait, I get it now. You should be using classes + inheritance instead of shoving everything inside a global module if you want to do this.

**Comment by nikitagupta55** [comment]
@ponyatov @kirbyfan64 Please help in resolving this issue : https://github.com/dabeaz/ply/issues/149

**Comment by dabeaz** [comment]
I'd have the parser build an AST and then use the AST as a jumping off point to do different things (run, syntax coloring, etc.).
