### ISSUE TITLE
Why is there set_lineno but not set_lexpos?

### ISSUE THREAD

**Issue by segevfiner** [dabeaz/ply#148]
Is there a reason that there is the function `set_lineno` for manually propagating line number information, but there isn't `set_lexpos` for manually propagating position information?

If it's not omitted on purpose, than this can be considered a request to add it. 😃

**Comment by dabeaz** [comment]
No idea.   I can add it, but if you need to track position information, it'd probably be better to do it in AST nodes or some other higher level data structure.

**Comment by dabeaz** [comment]
Added.
