### ISSUE TITLE
Ply does't work with python3 bytes/byte-arrays as input

### ISSUE THREAD

**Issue by tzeppy** [dabeaz/ply#154]
It seems to assume the input has already been unicode decoded.   I'm trying to write a ply parser for PDF files, and am having issues with the stream objects.

It would be a great enhancement to also allow all regex's to be specified as byte-arrays. (the re module allows this)

-Torsten

**Comment by dabeaz** [comment]
At one point in the distant past, PLY may have supported bytes as input, but it seems broken at the moment (and has likely been broken for quite some time).   If working with raw bytes, I'd strongly advise decoding the input into text using .decode('latin1') and writing the parser to assume normal text strings instead. 

I don't know how to easily fix PLY to support byte-strings given that they are rejected as doc-strings  and there are too many other things that would have to be changed to make it work.
