### ISSUE TITLE
Using yacc table file with newer ply version generates warning

### ISSUE THREAD

**Issue by olebole** [dabeaz/ply#155]
Hi,

I am the Debian maintainer of the [astropy](https://github.com/astropy/astropy) package, which uses ply on a few places. 
In the package, the yacc table files are generated at build time (or delivered with the source) and then installed together with the rest of astropy. Currently, the build happened with version 3.10.
At run time, there may however a different version of ply be used; currently this is 3.11. This [leads to a warning](https://ci.debian.net/data/autopkgtest/unstable/amd64/p/python-drizzle/20180221_205055/log.gz)
```
WARNING: yacc table file version is out of date
```
with an attempt to regenerate the file (which fails, since the user has no write permission in the installed package). The package itself however seems to work fine, as far as I can see it from the CI test.
I am now unsure what to do: shall I use exactly the same ply version as the one used to build the table file? Or otherwise, could the warning be avoided?
How sensitive is ply against using newer versions?

(This is a follow-up to issue astropy/astropy#7228)

**Comment by dabeaz** [comment]
The parsing table file generated by PLY is not something that should be packaged and included in a distribution to other people unless you want to pin everyone to a very specific version of PLY.  It's probably better to not include it and have PLY generate it on installation.  Or to use PLY in a way that it doesn't write the file in the first place.

**Comment by olebole** [comment]
In Debian, astropy and ply are independent packages, and can be upgraded independently.So, after the installation of astropy, the user may update ply.
This is specifically what happened when I recognized the problem -- it happened after ply upgraded to version 3.11 in Debian unstable.

**Comment by stefanor** [comment]
@olebole: I think the problem here was that you weren't using `dh_python3-ply`. I filed https://salsa.debian.org/debian-astro-team/astropy/merge_requests/1

**Comment by olebole** [comment]
@stefanor I agree; using `dh_pythonX-ply` seems to solve the problem (untested, since now it uses the actual version). Therefore, this issue can be closed.
