### ISSUE TITLE
parser table not written to `yacc` argument `outputdir`

### ISSUE THREAD

**Issue by johnyf** [dabeaz/ply#164]
Before ebf2d286d5dfc4cd255d523366f067df6ee48d14 (#141), the call [`ply.yacc.yacc(module=self, tabmodule='foo_parsetab', outputdir='./', write_tables=True, ...)`](https://github.com/dabeaz/ply/blob/0f398b72618c1564d71f7dc0558e6722b241875a/ply/yacc.py#L3216-L3218) for a parser defined as a class (`self` is the class instance) dumped the parser tables in the file `./foo_parsetab.py`, ignoring any existing tables under `site-packages`. This was useful to dump tables in a test directory, when testing an installed package.

Using ebf2d286d5dfc4cd255d523366f067df6ee48d14, the module's package is found by:

https://github.com/dabeaz/ply/blob/0f398b72618c1564d71f7dc0558e6722b241875a/ply/yacc.py#L3243

so that later:

https://github.com/dabeaz/ply/blob/0f398b72618c1564d71f7dc0558e6722b241875a/ply/yacc.py#L3264-L3269

`pkg` is not `None` any more, and `tabmodule` becomes `'package.foo_parsetab`. As a consequence, the table module is imported from under `site-packages`, the table hasn't changed (same signature), so nothing is done, and the function `yacc` returns:

https://github.com/dabeaz/ply/blob/0f398b72618c1564d71f7dc0558e6722b241875a/ply/yacc.py#L3293-L3299

In contrast, before ebf2d286d5dfc4cd255d523366f067df6ee48d14, `pkg is None`, so the `tabmodule` remains as given, not found, and thus created at the specified directory.

Which one is the intended behavior? Previously, the argument `outputdir` was effective, whereas now it is ignored, unless I `rm` the existing `foo_parsetab.py` from `site-packages`, in which case the tables are dumped to the given `outputdir` (as was the previous behavior). These two results:

- ignoring `outputdir` if `foo_parsetab.py` exists under `site-packages`
- dumping to `outputdir` otherwise

seem to be quite different, resulting in context-dependent behavior. It would be convenient to be able to specify the `outputdir` explicitly, and have the tables definitely written there if `write_tables=True`.

In terms of releases, `ply == 3.10` has the old behavior, and `ply == 3.11` the new behavior.

**Comment by dabeaz** [comment]
The intended behavior is for table files to be in the same directory as where the corresponding source code is found.  However, please just run with write_tables=False and be done with all problems related to this.

**Comment by johnyf** [comment]
Thank you for noting this, I realize that I relied on behavior that was not intended. I will avoid this usage of `outputdir` and `write_tables` in tests (for other cases, with source and tables in the same directory, writing tables has worked well).
