### ISSUE TITLE
AttributeError: 'module' object has no attribute '_tabversion'

### ISSUE THREAD

**Issue by pudo** [dabeaz/ply#165]
Getting this:

```
  File "ply/yacc.py", line 3293, in yacc
    read_signature = lr.read_table(tabmodule)
  File "ply/yacc.py", line 1987, in read_table
    if parsetab._tabversion != __tabversion__:
```

FWIW, using ply via https://github.com/mailgun/flanker. This occurs in their email address parser.

**Comment by dabeaz** [comment]
There is probably a very old file 'parsetab.py' somewhere on the Python path.

**Comment by pudo** [comment]
Hm, it can't be from a prior install (this is happening in Docker), is there any chance this is being generated wrongly by application using it? Thanks for your advice!

**Comment by dabeaz** [comment]
The whole parsetab.py/_tabversion aspect of PLY is something that has been around for a pretty long time at this point (maybe more than 10 years).   The only way to debug this might be to print out the value of "parsetab"  (the module) and see what filename it shows for the import.  Then, go look at that.  Perhaps the file needs to be deleted.
