### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by toddrme2178** [dabeaz/ply#169]
I am trying to package ply for openSUSE. However, there is no license file I can find, either in the github or tarball. In order for people to know how they can use your code it is really important to have a license file. Would it be possible to add one? Thank you.

**Comment by dabeaz** [comment]
The README file has the license in it.

**Comment by toddrme2178** [comment]
According to the official python packaging guidelines, for legal reasons all packages [should have a separate license file](https://packaging.python.org/guides/distributing-packages-using-setuptools/#license-txt):

> Every package should include a license file detailing the terms of distribution. In many jurisdictions, packages without an explicit license can not be legally used or distributed by anyone other than the copyright holder. If you’re unsure which license to choose, you can use resources such as GitHub’s Choose a License or consult a lawyer.

**Comment by dabeaz** [comment]
I typically make a new release of PLY about every 12-24 months.   If it is important to have a separate license file, someone should submit a pull request for it and I'll consider it for the next release cycle.
