### ISSUE TITLE
token lineno is not getting updated inside lex.py

### ISSUE THREAD

**Issue by shaehn** [dabeaz/ply#172]
I am experimenting with the rpcgen.py code from the kofemann/pynfs repository on github. I have replaced the older 'ply' folder contents with the latest from this repository. When I run rpcgen.py on a file that I have it generates the following:

Output' '.\rpcgen.py' './IPDSRPC.xx'
Input file is ./IPDSRPC.xx
Will use output files IPDSRPC_const.py, IPDSRPC_type.py, and IPDSRPC_pack.py
Syntax error at ',' (lineno 1)
Syntax error at ',' (lineno 1)
Syntax error at ',' (lineno 1)
Syntax error at ',' (lineno 1)
Ignoring program IPDSRPCPROG = 390927

As you can see, there are multiple errors which I know are on different lines in the file, but the reporting mechanism only shows _lineno_ set to 1.

I looked at the rpcgen.py **t_newline**(t) function which is called within the lib.py **token** function and noted that it was updating the t.lineno of the token passed in. So then I examined lex.py, in the **token** function, I saw that there was a state variable called _self.lineno_ that never gets updated. It is used to populate each new token created by the function. So I found that when I made the following change to lex.py.

![image](https://user-images.githubusercontent.com/13596544/40989584-46156ca6-68bc-11e8-9657-0d7905934908.png)

I would now get the expected output, which now has the correct line numbers.

Output' '.\rpcgen.py' './IPDSRPC.xx'
Input file is ./IPDSRPC.xx
Will use output files IPDSRPC_const.py, IPDSRPC_type.py, and IPDSRPC_pack.py
Syntax error at ',' (lineno 47)
Syntax error at ',' (lineno 64)
Syntax error at ',' (lineno 72)
Syntax error at ',' (lineno 91)
Ignoring program IPDSRPCPROG = 390927

**Comment by ponyatov** [comment]
You should define a special rule for end line parsing:
```## count line number
def t_newline(t):
    r'\n+'
    t.lexer.lineno += len(t.value)```

The special rule is better than embedded in a library, as you can process special cases like mixed Linux/Windows end lines, or some special cases.
