### ISSUE TITLE
yacc fails if sys.stderr is not available

### ISSUE THREAD

**Issue by sopoforic** [dabeaz/ply#175]
If in an environment without sys.stderr (e.g. pythonw), yacc will fail if it tries to write any log messages (e.g. for unused terminals).

This can be worked around in python 3.5+ by wrapping things with `contextlib.redirect_stderr`, but it should be handled in ply.

**Comment by dabeaz** [comment]
All error reporting is via Logger objects which can be supplied using the `errorlog` keyword argument to `yacc()`.   Use that to control or suppress error output from PLY.

**Comment by sopoforic** [comment]
That does fix the problem--I had thought due to e.g. [yacc.py:618](https://github.com/dabeaz/ply/blob/master/ply/yacc.py#L618) that it wouldn't be enough, but it looks like those lines won't be reached under normal conditions.

However, I'm not trying to control or suppress error output. I don't care what happens to those messages; I just want PLY not to crash when invoking `yacc` inside pythonw (which I coincidentally accomplish by redirecting the output).

Solving the problem by changing args to `yacc` means modifying my dependencies according to the current runtime environment, or modifying them to inspect the environment and create a dummy for the `PlyLogger` if needed. But then every module that wants to invoke `yacc` and which could possibly be run in an environment without `stderr` must know about the shape of these internal `PlyLogger` objects and individually implement the replacement.

By implementing a fix in PLY, anyone without `stderr` that wants these error messages can still pass an appropriate logger to `yacc`, but those who don't need them (e.g. I have a `p_error` function that deals with these) will be able to use `yacc` without a crash.

**Comment by dabeaz** [comment]
My comment about using logging still stands.    All output from PLY is handled via logging and if you want to control it, you should pass an appropriate logger that's configured to do what you want.  The interface to Logging is the same as Python's standard `logging` module so you'd normally use that:

    import logging
    log = logging.getLogger('ply')
    ...
    yacc(errorlog=log)

For what it's worth,  you can use `ply.yacc.NullLogger` to create a Logger object that does nothing.
