### ISSUE TITLE
Is it possible to apply lex and yacc for SQL stored procedures ?

### ISSUE THREAD

**Issue by owancy99** [dabeaz/ply#177]
Hi!

        I already use ply.lex and add some custom to produced tokens from sql stored procedure. The sample result like as below:

(CREATE,'Create',1,0)
(FUNCTION,'FUNCTION',1,7)
(LBRACKET,'[',1,16)
(ID,'dbo',1,17)
(RBRACKET,']',1,20)
(PERIOD,'.',1,21)
(LBRACKET,'[',1,22)
(ID,'fBDMSGetOrderLocationDept',1,23)
(RBRACKET,']',1,48)
(LPAREN,'(',2,55)
(VAR,'@P_PatientOrderDetailUID',3,64)
(ID,'INT',3,89)
...
(SELECT,'SELECT',19,547)
(VAR,'@V_OrderDept',19,554)
(EQUALS,'=',19,567)
(ID,'B',19,569)
(PERIOD,'.',19,570)
(ID,'Code',19,571)
(FROM,'FROM',19,576)
(ID,'Location',19,581)
(ID,'A',19,590)
(COMMA,',',19,591)
(ID,'CostCode',19,592)
(ID,'B',19,601)
(WHERE,'WHERE',19,603)
(ID,'A',19,609)
(PERIOD,'.',19,610)

But I don't know how to use ply.yaac to parse the tokens as above to build SQL grammar.  May you guide me about this,please?

**Comment by dabeaz** [comment]
The `parse()` method of the parser created by yacc() allows a custom lexer to be supplied.  That lexer needs to provide a `token()` method that returns the next token or `None`.  Tokens need to provide "type", "value", "lineno", and "lexpos" attributes.  You could always bake your own thing:

    class MyToken(object):
          def __init__(self, type, value, lineno, lexpos):
               self.type = type
               self.value = value
               self.lineno = lineno
               self.lexpos = lexpos

class MyLexer(object):
      def __init__(self, toks):
            self.tokiter = iter(toks)
      def token(self):
            return next(self.tokiter, None)

    # Usage in yacc
    lexer = MyLexer(toks)
    result = parser.parser(lexer=lexer)

**Comment by owancy99** [comment]
Thank you for your advice. But I still unclear about those class.  I give a part of my current source code for more information. Token already define and build as below:

import ply.lex as lex

# Reserved words
action = ('CREATE','ALTER','DROP','INSERT','UPDATE','DELETE','SELECT')
pgmtype = ('PROCEDURE','FUNCTION','VIEW')
mathop = ('COUNT','TOP','SUM','AVG','MIN','MAX')
clause = ('WHERE','ORDER','GROUP','BY','HAVING','VALUES')
setop = ('NOT','AND','OR','IN','UNION')
direction = ('INTO','FROM')

reserved = action + pgmtype + mathop + clause + setop + direction + (
    'DECLARE', 'INTO', 'SET','TABLE','INNER','OUTER','JOIN', 'DISTINCT', 'OPEN', 'FETCH', 'NEXT', 'CLOSE',
    'WHILE', 'IF', 'ELSE','AS', 'BEGIN', 'END','RETURN','EXEC'
)

tokens = reserved + (
    # Literals (identifier, integer constant, float constant, string constant, char const, variable)
    'ID', 'TYPEID', 'INTEGER', 'FLOAT', 'STRING', 'CHARACTER', 'VAR',
...
...
# Comment (C-Style)
def t_COMMENT(t):
    r'/\*(.|\n)*?\*/'
    t.lexer.lineno += t.value.count('\n')
    #return t

def t_CMT1(t):
    r'--.*\n' 
    t.lexer.lineno += 1
    #return t


def t_NEWLINE(t):
    r'\n'
    t.lexer.lineno += 1
...
lexer = lex.lex()

def run():
    lex.runmain(lexer)

if __name__ == "__main__":
    run()

When object class MyLexer should be applied after that? Is object parser derived from class yacc? I'm confuse about this.

Thank you very much

**Comment by owancy99** [comment]
I already find other solution to solve it. OK
