### ISSUE TITLE
Pass on production still places a None in the parse tree.

### ISSUE THREAD

**Issue by EricGebhart** [dabeaz/ply#179]
Hello. I'm implementing a lisp and I'd like to be able to have a form comment, like the ones in clojure.  _#\_(sexprs)_

  or _(comment sexprs)_  should be ignored. I have a production that works, but I really want it to be completely ignored and not put a None in the parse tree.

This is also just an experiment.  Ideally  *#\_*  would set a state in the parser where the next
form is thrown away. For now I'm just looking for *#\_(.....)*  but Ideally it would change the state so the next match is tossed out.

As it is, I can not seem to toss out a match so that it does not go into the parse tree in some fashion.
```
    def p_ignoreform(self, p):
        'ignoreform : LIGNOREFORM sexprs RPAREN'
        pass
```
This is also the most efficient place for this, I can create a special ignore object to put in the parse tree, but I would still have to walk the tree afterward to remove them. It would be much better to not put anything there in the first place.

So `(+ 1 2 #_(* 5 10) 4)`  would evaluate to `7`.   in the middle it needs to be `(+ 1 2 4)`  not
`(+ 1 2 None 4)`

None is another valid value that I can't filter out.  I did have it doing this. at least I know
what to ignore when I evaluate...

```LIST(Atom(+), 1, 2, Ignore(Atom(*), 5, 10), 4) ``` 

 but I'd have to walk the parse tree a second time before evaluation to remove them.   I guess that's not awful, but it seems better to do it when it parses.

**Comment by EricGebhart** [comment]
So maybe the best thing is to change state in the lexer and throw away the tokens there....

**Comment by dabeaz** [comment]
The construction of parse trees falls outside the scope of how yacc operates.   Parsing rules represent substitutions--the symbols on the right hand side of a parsing rule are replaced by the symbol on the left hand side.  All symbols have an associated value which is whatever you happen to make it (or None if you do nothing). 

If a parser is to ignore a parsing rule, the handling of that would have to be programmed into the actions of your various parsing rules.  That is, you'd have to explicit check for it and take action as appropriate to make sure it doesn't end up getting put in the parse tree.   This handling would likely occur at a higher level--for example in higher-level parsing rules that rely on "ignoreform" in your example.
