### ISSUE TITLE
FR: allow omitting space before colon in BNF comments

### ISSUE THREAD

**Issue by dcolascione** [dabeaz/ply#181]
Right now, one must write `nonterminal : thing thing`, but in some cases, it feels more natural to write `nonterminal: thing thing` instead. Note that in the latter case, we omit a space before the `:`. PLY currently rejects the latter string, but maybe it shouldn't.

**Comment by dabeaz** [comment]
PLY is purely in maintenance mode at this time.  I'm not going to make changes to the grammar rule syntax at this point.
