### ISSUE TITLE
Rewrite yacc.parse as generator function (using yield)

### ISSUE THREAD

**Issue by ponyatov** [dabeaz/ply#188]
I need a parser works as pure lexer:
1. feed a string to be parsed with say
```
parser = yacc.yacc()
parse_generator = parser.parse('source code')
```
2. loop until end of passed source
```
while True:
    element = parse_generator.next()
    if not element: break
    < do processing >
```

**Comment by dabeaz** [comment]
The parser already runs until reaches the end of the passed source.   If there is some kind of processing to be done, it can be done in the parsing rules:

    def p_elements(p):
        '''elements : elements element'''

    def p_elements(p):
        '''elements : element'''

    def p_element(p):
        '''
        element : ...
        '''
        <do processing>

**Comment by Mazdaywik** [comment]
If you write FORTH implementation you must use lexer without parser because FORTH has not a syntax.

Your want:
> ```Python
> while True:
>     element = parse_generator.next()
>     if not element: break
>     < do processing >
> ```

There are [example](http://www.dabeaz.com/ply/ply.html#ply_nn4) in official documentation of PLY:

```Python
# Test it out
data = '''
3 + 4 * 10
  + -20 *2
'''

# Give the lexer some input
lexer.input(data)

# Tokenize
while True:
    tok = lexer.token()
    if not tok: 
        break      # No more input
    print(tok)
```

It is really what you want.

**Comment by dabeaz** [comment]
If you need to interact with the lexer during parsing, do it from within the grammar rules as needed.  PLY is currently in maintenance-only development.  As such, I'm not changing the API for parsing.
