### ISSUE TITLE
singleline sticky when used in token pattern

### ISSUE THREAD

**Issue by thorslug** [dabeaz/ply#198]
Looks like any use of the SINGLELINE flag. e.g. `r"(?smx)some_pattern"` in a token pattern expression, affects other tokens that don't use that flag, i.e. makes those patterns use SINGLELINE as well, but this seems wrong.

Using PLY v 3.11

**Comment by thorslug** [comment]
I see the problem: this behavior is a consequence of PLY's construction of a "master regex", where the token regex patterns get OR'ed together and THEN compiled.  Here's the code from `lex.py`:

`def _form_master_re(relist, reflags, ldict, toknames):
    if not relist:
        return []
    regex = '|'.join(relist)
    try:
        lexre = re.compile(regex, reflags)
`

I see this as a PLY design flaw: it means you can't use inline flags in token patterns without those flags potentially being compiled in to neighboring token patterns.

**Comment by dabeaz** [comment]
This is not something that will ever be fixed in PLY.   Don't use inline flags.
