### ISSUE TITLE
Close yacc debugfile

### ISSUE THREAD

**Issue by randallpittman** [dabeaz/ply#200]
Short summary: When creating the `PlyLogger` for the `debuglog`, the file (e.g. `parser.out`) that gets opened should be closed.

I discovered this because I was getting `ResourceWarning: unclosed file <_io.TextIOWrapper name='/data/Development/cdlparser/parser.out' mode='w' encoding='UTF-8'>` in a `unittest` suite. The weird thing is that I only get that warning when using a parser that is a subclass of another parser thats in a different module. If the parsers are in the same module, I don't get the warning. But I had to put the subclass in a different module or else the parent class's tokens would take precedence over the subclass's tokens. But that's another issue.

**Comment by bfontaine** [comment]
👍 on this. I’m writing tests for [edn_format](https://github.com/swaroopch/edn_format) and I want to assert that the file is or is not present in a unit test but I can’t do so because the file may not have been written on disk yet.

**Comment by yelly** [comment]
This seems to be resolved...
