### ISSUE TITLE
Token objects in yacc parser

### ISSUE THREAD

**Issue by ponyatov** [dabeaz/ply#203]
I use this source code representation object:

```
class Source:
	def __init__(self,V):
		self.type = self.__class__.__name__.lower()
		self.value = V
		self.nest = []
	def __repr__(self):
		return self.dump()
	def dump(self,depth=0):
		S = self.pad(depth) + self.head()
		for j in self.nest: S += i.dump(depth+1)
		return S
	def head(self):
		return '<%s:%s>' % (self.type, self.value)
	def pad(self,N):
		return '\n' + '\t'*N
```
and iherit other types of syntax elements. I specially add type and value fields to be compatible with yacc parser API.

I define tokens in this like way and return contstructed objects as tokens:
```
class Comment(Source): pass
def t_comment(t):
	r'//[^\n]*|\/\*.*?\*\/'
	return Comment(t)

class ppInclude(Source): pass
def t_ppinclude(t):
	r'\#include'
	return ppInclude(t)

class String(Source): pass
def t_string(t):
	r'\".*?\"'
	return String(t)

class Number(Source): pass
def t_number(t):
	r'[0-9]+'
	return Number(t)

class Symbol(Source): pass
def t_symbol(t):
	r'[a-zA-Z0-9_]+'
	return Symbol(t)
```

**Comment by ponyatov** [comment]
But when I try to use simple parser rules, I get strings (.value fields) but not token objects what I want:
```
def p_ex_include(p):
	' expression : ppinclude string '
	p[0] = p[1].nest.append(p[2])
```

**Comment by ponyatov** [comment]
Does PLY have tweaking options let me avoid .value fetching and work directly with the token objects?

**Comment by dabeaz** [comment]
Instead of writing token rules that return instances of your custom objects (as tokens), you should set the token value attribute to be those objects.  For example:

    class Comment(Source): 
        pass

    def t_comment(t):
        r'//[^\n]*|\/\*.*?\*\/'
        t.value = Comment(t.value)
        return 

References to ``comment``  in the parser will now hold your ``Comment`` instance.

**Comment by ponyatov** [comment]
Yes, I know it, and it works ok, but the problem is in another part: 
parser rules deconstruct values if they were used deeply
(I fixed the source code sample above to show the problem)

In `p_include()` rule I see right objects tranfered from token .values

In more general rule `p_repl_recur()` I already see destructed objects

**Comment by dabeaz** [comment]
The `.value` attribute of tokens is whatever you decide it should be and that's what gets passed to the parsing rules in the parser.   If you want something other than a string, you set `.value` to whatever it is that you want.  There is no option to make PLY behave differently.

**Comment by ponyatov** [comment]
Ok, but why `p[0]` assignment was lost?

**Comment by dabeaz** [comment]
It could be a typo (fixed just now) in my example, but make sure all token rules end with "return t" and not a bare "return".   PLY is not violating Python's rules for reference counting though.  If things are being destroyed or None is coming back, there is a problem in either returning a value (or not) or not saving something elsewhere.
