### ISSUE TITLE
Question: How to add rules to parser program on the fly?

### ISSUE THREAD

**Issue by bifunctor** [dabeaz/ply#205]
I have a parser program with a set of rules. When a statement is called, I want to add new rules to my parser. Its just like an import statement. Is there a way I can add rules to parser program on the fly (While the parser is running)?

**Comment by dabeaz** [comment]
It's can't be done in any practical sense.   The whole parser is driven by a table that encodes a giant state-machine along with an internal parsing stack.   Adding new rules would require a regeneration of the entire table and a full reset of the parser.      What kinds of rules are being added?

**Comment by Obround** [comment]
The rules being added would be, for example operators. When the statement is called, the parser will be able to parse operators such as `+`, `-`, etc.

**Comment by refi64** [comment]
You could instead maybe use one token type for each precedence level, use those types in the parsing rules, then emit the proper token types from the lexer.

**Comment by Obround** [comment]
@refi64 -- Thanks, its a very good idea. The thing is, I can't do that with a lot of rules.

**Comment by Obround** [comment]
@dabeaz -- Is there a way to add new lexers and parsers *while* the parser is running?

**Comment by dabeaz** [comment]
I implemented something sort of like this awhile back (in SLY) where one could define new operators.  It worked by defining a token in the Lexer that generally matched any possible operator (i.e., operators were defined by a set of allowed symbols much like an identifier or a number).   The lexer then allowed specific operator patterns to be registered to return one of 10 different, but more specific operator tokens (OP0, OP1, OP2, OP3, ... OP9).    In the parser, these were each assigned a different precedence level and handled through some rather generic grammar rules like:

    binary_operator : expr OP0 expr
                    | expr OP1 expr
                    | expr OP2 expr
                    | expr OP3 expr
                    ...

Each OPn token could potentially be many different things.  For example, you could have + and - assigned to OP4, * and / assigned to OP5, etc  (the exact operator text is something that you'd have to examine or deal with to know more information).   

One critical thing about this is that all of the token names, precedence tables, and parsing rules were defined in advance.   The only dynamic part of it was a table in the lexer to map specific patterns of known symbols to specific operator tokens--that could be changed at runtime.   

For some context, I was trying to implement something similar to the ability to define new infix operators in Haskell.

**Comment by Obround** [comment]
@dabeaz -- Thanks, but 2 things:
- I want to use ply (Because I have already made a lot of code in it)
- I don't want the tokens to be defined in advance.

>  Is there a way to add new lexers and parsers while the parser is running?

If I can add lexers and with their parsers on the fly, I can add them when the statement is called.

**Comment by Obround** [comment]
@dabeaz -- Is there a way I can efficiently regenerate the underlying parsing table? I have an idea, but I amn't sure it'll work. My idea is that when the statement is called, the parser file will import itself and add new rules.

**Comment by dabeaz** [comment]
No idea.  I've never done this, nor would I try to do it this way.
