### ISSUE TITLE
How to define tokens for greater-equal and greater?

### ISSUE THREAD

**Issue by andreasg123** [dabeaz/ply#207]
I'm trying to figure out how to fix an issue with a Matlab to Python compiler that doesn't parse `>=` correctly. It defines tokens for both `>=` and `>` but the `>` token is always chosen: https://github.com/victorlei/smop/blob/master/smop/lexer.py#L63

Is there a way to define a token that is the prefix of another token?

**Comment by Pythux** [comment]
Hi,
the first matching rule will be chosen if I'm not mistaking, so it's better to catch it all in a function and split it at your need:


```python
comparison = {
    '<': 'LT',
    '<=': 'LE',
}
tokens += list(comparison.values())

def t_Comparison(t):
    r'(<=|<)'
    t.type = comparison[t.value]
    return t
```
something like that should do, note the "<=" match before "<" in the *or* regex `r'(<=|<)'`
then set token type to the corresponding one

ps: function check regex first, in order of definition
