### ISSUE TITLE
Question: Similar rule parsing

### ISSUE THREAD

**Issue by bifunctor** [dabeaz/ply#208]
How do you parse *very* similar rules in ply? Suppose a have a code that looks like this:

```python
def p_print_smt(t):
    '''print_smt :
                 | PRINT LPAREN expression RPAREN SEMI
                 | PRINT LPAREN SYMBOL func_args RPAREN SEMI'''
    exec_type = 0
    
    try:
        t[6]
    
    except:
        exec_type = 1

    if exec_type == 0:
        #Do something
       pass
    
    elif exec_type == 1:
        #Do something
       pass
    
    print(t[0])
```

Here is the supposed code to parse:

```python
print(my_symbol arg1, arg2)
```

When the parser parses that piece of code, it should go to the `PRINT LPAREN SYMBOL func_args RPAREN SEMI` rule but instead goes to the `PRINT LPAREN expression RPAREN SEMI` rule. How do I direct the parser so that it goes to the rule I want it to go to?

**Comment by dabeaz** [comment]
Split it into two functions:

    def p_print_stmt_1(p):
         'print_smt : PRINT LPAREN expression RPAREN SEMI'

    def p_print_stmt_2(p):
        'print_smt :  PRINT LPAREN SYMBOL func_args RPAREN SEMI'

Of course, if there are shift/reduce or reduce/reduce conflicts, all bets are off.  You'll need to debug your grammar for that.

**Comment by Obround** [comment]
@dabeaz -- Still not working... It still tries to execute `p_print_stmt_1`. I found a way to make it work, though I don't like it. If I change `p_print_stmt_2` to this:

```python
def p_print_stmt_2(p):
    'print_smt : RANDOM_TOKEN LPAREN SYMBOL func_args RPAREN SEMI'
```
Then it works, as I change the `PRINT` token to another token I made called `RANDOM_TOKEN`. Is there some other way I can make this work while still keeping the `PRINT` token in it?

**Comment by dabeaz** [comment]
If a grammar rule is not activating, there is something wrong with your grammar and/or lexer.   Either you're not tokenizing things correctly or your grammar has shift/reduce or reduce/reduce conflicts.  To debug the latter, you're probably going to to need to look at the parser.out file.

**Comment by Obround** [comment]
@dabeaz -- What do you mean by this:
> You're not tokenizing things correctly

How does that look?

**Comment by dabeaz** [comment]
Your tokenizer isn't producing the tokens that are required by the grammar rule. Maybe a bad regex or there is ambiguity (i.e., there more than one token rule that matches the same input text---only one will be used).

**Comment by Obround** [comment]
My code doesn't seem to have any issues with tokenizing and very minimal issues with shift/reduce or reduce/reduce conflicts. Is this some kind of bug? If it helps, at the bottom of my `parser.out` file I have these few issues:

```
WARNING: shift/reduce conflict for RBRACKET in state 74 resolved as shift
WARNING: shift/reduce conflict for LBRACKET in state 117 resolved as shift
WARNING: shift/reduce conflict for LPAREN in state 117 resolved as shift
WARNING: shift/reduce conflict for SYMBOL in state 117 resolved as shift
WARNING: shift/reduce conflict for LBRACKET in state 133 resolved as shift
```

**Comment by dabeaz** [comment]
The presence of a shift/reduce conflict indicates an ambiguous grammar.   It means that there is more than one way to parse a given input.  You're getting such a warning for the SYMBOL token which is part of the rule that you claim isn't firing.  You need to look at the parser.out file (and specifically state 117 for the above output) to see what is happening.  You've very likely got some kind of duplication.  For example, maybe 'SYMBOL funcargs' matches some input that is exactly the same as a valid expression.

PLY does not support GLR.
