### ISSUE TITLE
Inclusive state does not follow token rule precedence

### ISSUE THREAD

**Issue by thorslug** [dabeaz/ply#209]
I believe "inclusive" lexer states are not working properly.  In my testing, once my "inclusive" lexer state was the active state, it was not returning tokens for the default INITIAL state as it should.  Inspection of the lex.py source code revealed that the regular expressions for the INITIAL state are added to the inclusive state **after** the master regex expressions are built for each of those states.  But this results in two undesirable outcomes in the resulting master regex for the inclusive state:

1. Any token rules using the `t_ANY` syntax are repeated, i.e. there are 2 copies of each of these in the master regex for this inclusive lexer state: one copy due to the state itself, and one copy due to the INITIAL state, and
2. The master regex does not observe the order in which the token rules are defined.

**Comment by thorslug** [comment]
I have a fix ready; would you give me push access?

**Comment by dabeaz** [comment]
Changing anything related to this is non-trivial and likely to have bad consequences if not considered carefully.  Please submit patches as a pull request so that it can be reviewed.

**Comment by thorslug** [comment]
Understood.  I'm currently using the code I submitted in the PR, and results are good.  I should add that I think this problem will manifest when you have token rules for the INITIAL state defined **before** those of the inclusive lexer state; here are the token rules I've got:

- 1 `t_ANY` rule
- 1 default rule
- 11 rules for one exclusive state
- 20 rules for another exclusive state
- 34 default rules
- 2 `t_ANY` rules
- **4 rules for the inclusive state**
- 2 default rules
- 2 `t_ANY` rules
- and finally the `t_error` rule
