### ISSUE TITLE
Ambiguous lex rules don't match longest rule

### ISSUE THREAD

**Issue by pmdwyer** [dabeaz/ply#213]
When using two rules that overlap on input, the lexer does not return the longest matching rule. For example, the following should print `LexToken(EXTENDED,'ply.lex',1,0)`. Instead, it prints
```
LexToken(IDENTIFIER,'ply',1,0)
LexToken(EXTENDED,'.lex',1,3)
```

Source:
```python
import ply.lex as lex
from ply.lex import TOKEN

tokens = (
  'SPACE',
  'IDENTIFIER',
  'EXTENDED'
)

t_SPACE = r'([ \t\r\f\v\n])'
t_IDENTIFIER = r'[\-_a-zA-Z]([\-_a-zA-Z0-9])*'
t_EXTENDED = r'([\-_a-zA-Z0-9]|\.)+'

lexer = lex.lex()
lexer.input('ply.lex')

while True:
  tok = lexer.token()
  if not tok:
    break
  print(tok)
```

**Comment by avlouis** [comment]
I have encountered similar issues.  It seems that the lexer prefers to match with the token with the longest regular expression.  In your example, it prefers to match IDENTIFIER over EXTENDED for this reason.  This behavior differs from the fairly standard behavior of greedily matching the longest token and preferring the token that was defined first when there is a tie for longest token.

**Comment by dabeaz** [comment]
The ordering of tokens defined by simple strings is only a simple heuristic (ordered by string length).  If you want precise control, define the tokens using functions instead (in which case tokens are matched in the precise order in which functions are defined in the file).

**Comment by avlouis** [comment]
Correct me if I am wrong, but ```Lexer.token``` will always return the token corresponding to the first match.  Standard lex behavior (from my experience) has been to return the token corresponding to the longest match with ties broken by the ordering.

**Comment by dabeaz** [comment]
Yes, it returns the first match.  However, this is the same behavior as regex matching with the Python re module--and the documented behavior of PLY.

**Comment by pmdwyer** [comment]
While defining the tokens as a function fixes the ordering issue, the issue of an incorrect match remains. Take the following for example:
```python
import ply.lex as lex
from ply.lex import TOKEN

tokens = (
  'SPACE',
  'IDENTIFIER',
  'EXTENDED',
)

space = r'([ \t\r\f\v\n])'
identifier = r'([\-_a-zA-Z])([\-_a-zA-Z0-9])*'
extended = r'([\-_a-zA-Z0-9]|\.)+'

@TOKEN(space)
def t_SPACE(t):
  return t

@TOKEN(identifier)
def t_IDENTIFIER(t):
  return t

@TOKEN(extended)
def t_EXTENDED(t):
  return t

lexer = lex.lex(debug=1)
lexer.input('indentifier not.identifier')

while True:
  tok = lexer.token()
  if not tok:
    break
  print(tok)
```
The output is 
```
LexToken(IDENTIFIER,'indentifier',1,0)
LexToken(SPACE,' ',1,11)
LexToken(IDENTIFIER,'not',1,12)
LexToken(EXTENDED,'.identifier',1,15)
```
Now, if the order of the functions is inverted, the tokens get matched as
```
LexToken(EXTENDED,'indentifier',1,0)
LexToken(SPACE,' ',1,11)
LexToken(EXTENDED,'not.identifier',1,12)
```
which is not preferred. The ordering is correct in the first case, but the matching is not correct. In the second case, the rules are in the incorrect order, and only the first rule gets matched. Is there a way to have overlapping/ambiguous rules where the rule with the longest matched token is called?

**Comment by dabeaz** [comment]
Tokenizing in PLY can best be described as prioritized choice.  If expr1 and expr2 are two different regular expressions, they are either going to be matched as (expr1 | expr2) or as (expr2 | expr1).   You can control the order by defining them as functions in the order that you want.  Matching stops with the first expression that happens to match.   This is standard behavior of the re module. The two expressions aren't combined into some kind of longer or different regex.  

If the two expressions happen to overlap, then that is a problem that you need to resolve yourself.  Write a single regex that matches the more general case and use a function to disambiguate the token into separate cases based on the match text.   An example of this is shown for identifiers in the docs.  https://www.dabeaz.com/ply/ply.html#ply_nn6
