### ISSUE TITLE
Avoid __file__

### ISSUE THREAD

**Issue by jayvdb** [dabeaz/ply#216]
See https://github.com/eliben/pycparser/issues/355

**Comment by dabeaz** [comment]
I'm no longer making PLY releases. This should be fixed by adding the appropriate __file__ attribute or vendoring PLY and modifying it in some manner.

**Comment by jayvdb** [comment]
@dabeaz , so this repo is now archived?  No more enhancements here?

**Comment by dabeaz** [comment]
PLY is free software. Meaning you are free to use it, copy it, or do what you want with it.  However, it also means that I am not obligated to provide free support, maintenance, or package-installable releases of it.   I might make occasional changes to it.  I might not.   See CONTRIBUTING.md

**Comment by jayvdb** [comment]
Sure you are not obligated to do anything. An issue doesnt mean *you* are obligated to do something, so why close it?  I've been fixing this specific problem in a bunch of repos, and would be happy to do it here also.
