### ISSUE TITLE
Add note that ply does not support Python with -OO

### ISSUE THREAD

**Issue by lambdalisue** [dabeaz/ply#225]
When Python has executed with [`-OO`](https://docs.python.org/3/using/cmdline.html#cmdoption-oo), all docstrings are removed and `SyntaxError: Can't build lexer` is raised.

If I turned on the logger, `No regular expression defined for rule...` messages are logged like
 
<img width="1244" alt="alisue-sandbox-windows-10 2020-03-31 22-59-00" src="https://user-images.githubusercontent.com/546312/78034839-38524280-73a3-11ea-8347-4f699683bf0b.png">

It's a bit difficult to find out why fails if users are not familiar with ply (like me) thus I think it would be helpful if README has a note about `-OO`.

**Comment by smpartlow** [comment]
See section 8 of https://www.dabeaz.com/ply/ply.html which describes running it first without -OO but specifying optimize=1 on lex and yacc.

**Comment by dabeaz** [comment]
Support for -OO is no longer provided in the current version.  Added note to docs.
