### ISSUE TITLE
Docstring typos

### ISSUE THREAD

**Issue by hugovk** [dabeaz/ply#226]
https://github.com/dabeaz/ply/commit/001fb206e9cbe5fea5c81924cc854984e6984131 has some typos:

> Because of PLY's reliance on doc-strings, it is not compatible with
`-OO` mode of the interpreter (which strings doc strings).  If you
want to support this, you'll need to write a decorator or some other
tool to attach doc strings to functions.  For example:

doc-strings -> docstrings

strings doc strings -> strips docstrings

doc strings -> docstrings

Re: https://www.python.org/dev/peps/pep-0257/

https://github.com/dabeaz/ply/compare/master...hugovk:fix-typos?expand=1 fixes them, plus "doc-strings" and "doc strings" in other files. I've not created a PR, as requested in the contributing guidelines.

**Comment by dabeaz** [comment]
Fixed
