### ISSUE TITLE
Is there any way to use ply.yacc without ply.lexer?

### ISSUE THREAD

**Issue by abreulima** [dabeaz/ply#227]
I made a lexer myself, and the syntax analyzer I'm trying to use the ply.yacc, but it looks like it's heavily dependent of the ply.lexer.

Is there any way to easily combine my lexer with the ply.yacc?

**Comment by dabeaz** [comment]
The `parse()` method has a `lexer` keyword argument to specify a lexer.   It must be an object that implements a `'token()` method that returns the next token.

**Comment by dabeaz** [comment]
Just as a note, I'm probably going to change this to use a generator/iterator based API.  PLY is so old, it predates the formalization of the Python iterator protocol.   That part should be modernized.

**Comment by abreulima** [comment]
Oh, that's nice to hear.

I solved my problem iterating over a list I already had.

`
    def token(self):

        if self.iterator < len(self.tokens_plyacc):
            t = self.tokens_plyacc[self.iterator]
            self.iterator = 1 + self.iterator
            return t

        else:
            return None
`
