### ISSUE TITLE
Looping through a production rule 

### ISSUE THREAD

**Issue by abreulima** [dabeaz/ply#229]
I'm making a while statement and I want to loop through an expression, and my code is similar to the code below

```
def p_write(p):
    '''write : WRITE LPAREN identifier_list RPAREN SEMICOLON'''
     print("I am here")

def p_repetitive(p):
    '''repetitive : WHILE LPAREN expression RPAREN compound'''
    
     for i in range(0, 5):
           p[5]
```

I'm trying to loop 5 times the production rule _write_.

but It displays _I am here_ once.

Am I missing something?

**Comment by dabeaz** [comment]
I don't follow.  How is p_write() supposed to be triggered here?

**Comment by abreulima** [comment]
There are more production rules, but I didn't write to make it easier to read, but make code has the following derivation.

**compound -> compound_list -> unlabeled_statement -> write**

So, in the case, above compound is p[5], that is write. I can achieve the write production production rule without problem, my issue is when I try to execute it again in a loop. It just executes once.
