### ISSUE TITLE
Running lex.lex() and yacc.parse() directly w/o an instance

### ISSUE THREAD

**Issue by clintolsen** [dabeaz/ply#230]
I started a project using PLY a few years ago, and I've adapted the calculator into a more complicated project.

My knowledge of the internal workings of Python and PLY are somewhat limited. In some of the examples (calculator in particular) `lex.lex()` _can_ be executed without assigning it to a variable, and `yacc.parse()` can be run directly rather than on an instance (e.g. `argparse`) and without specifying a lexer object.

Can you elaborate what is going on here behind the scenes?

**Comment by dabeaz** [comment]
It's a global variable.   You should use the more explicit form of `lexer = lex.lex()` and `parser = yacc.yacc(lexer=lexer)` instead.

**Comment by clintolsen** [comment]
Thanks for the speedy reply.

It's not required even to assign `lex.lex()` to anything and `yacc` finds it. If you don't create a global `lexer` things work fine. That's more of what I was wondering about. It's like there's some weird introspection going on which is like voodoo magic.
