### ISSUE TITLE
Regular expression like r'(?!udp)[a-zA-Z_][a-zA-Z0-9_-]*' does not work as a token identifier

### ISSUE THREAD

**Issue by antonyjesto** [dabeaz/ply#231]
I created a token with regular express r'(?!ip|ipv6|icmp|igmp|pim|tcp|udp)[a-zA-Z_][a-zA-Z0-9_-]*'. The idea is "ip|ipv6|icmp|igmp|pim|tcp|udp" are the set of keywords. So the regular expression will not match any strings starting with any of "ip|ipv6|icmp|igmp|pim|tcp|udp"

But when I tried to tokenize 'udp udp-telnet', the output is as 
=>python3.8 aa.py
LexToken(PROTOCOL,'udp',1,0)
LexToken(PROTOCOL,'udp',1,4)
Illegal character '-'
Entire line: LexToken(error,'-telnet',1,7)
LexToken(PORT_NAME,'telnet',1,8)

I was expecting udp-telnet will be taken as a token PORT_NAME. The complete code I tried is as below.

```
import ply.lex as lex
import ply.yacc as yacc

port = ""
parse_result = False

######################### Lexer starts #####################################
tokens = (
    'PROTOCOL',
    'PORT_COMPARATOR', 'PORT_NAME'
)

t_PROTOCOL = r'(ip|ipv6|icmp|igmp|pim|tcp|udp)'
t_PORT_COMPARATOR = r'(eq|neq|lt|gt)'
def t_PORT_NAME(t):
    r'((?!ip|ipv6|icmp|igmp|pim|tcp|udp)[a-zA-Z_][a-zA-Z0-9_-]*)'
    t.value = t.value
    return t

t_ignore = " \t"

def t_newline(t):
    r'\n+'
    t.lexer.lineno += t.value.count("\n")

def t_error(t):
    print("Illegal character '%s'" % t.value[0])
    print("Entire line: %s" % t)
    t.lexer.skip(1)

######################### Parser ends #####################################

def ace_parse(ace_string_input):
  # Build the lexer
  lexer = lex.lex()

  lexer.input(data)
  for tok in lexer:
    print (tok)

if __name__ == "__main__":
  data = 'udp udp-telnet'
  ace_parse(data)

```

**Comment by marmarmarques** [comment]
"udp-telnet"
"udp" matches (?!ip|ipv6|icmp|igmp|pim|tcp|udp)
"telnet" matches [a-zA-Z0-9_-]*
but [a-zA-Z_] doesn't match "-"
just remove [a-zA-Z_]
