### ISSUE TITLE
Storing the result of the parser in a variable.

### ISSUE THREAD

**Issue by jack17529** [dabeaz/ply#232]
Hi, I would like to store the value returned by `parser.parse(s)` in a variable, but it returns a nonetype object. Can you please guide me how I can store the value in an int variable in Python?

**Comment by FLHerne** [comment]
In each grammar rule function `def p_something(p): ...`, you should assign a value to `p[0]` if you wish to record it. Symbols in the parse tree can access the values of their children, and ultimately the value set in `p[0]` by the starting symbol will be returned by `parse()`.

See [the example in the documentation.](https://www.dabeaz.com/ply/ply.html#ply_nn24)

**Comment by jack17529** [comment]
@FLHerne I already have read that in documentation. I looked again in my code, this is not what I am asking. I want to store the value in the end returned in a variable. If I misunderstood you, please show me the code.

**Comment by dabeaz** [comment]
The value returned by `parser.parse()` needs to be stored in `p[0]`.  You then use:

`somevar = parser.parse(whatever)`

If the `parse()` method is returning `None`, then values aren't being propagated or saved in `p[0]` correctly.

**Comment by jack17529** [comment]
@FLHerne @dabeaz I was following a differently written code. Thanks for the help.
