### ISSUE TITLE
Please add .gitattributes

### ISSUE THREAD

**Issue by ned14** [dabeaz/ply#244]
As reported at ned14/quickcpplib#12, the need to poke a .gitattributes into submodule ply is problematic for some.

A suitable .gitattributes can be found at https://github.com/ned14/quickcpplib/blob/master/.gitattributes.

**Comment by dabeaz** [comment]
Why is this needed?

**Comment by ned14** [comment]
It is explained in the original issue, but in short, some package managers refuse to package a repo which git says is dirty. As my repo submodules the ply repo, I have to poke in a .gitattributes so CRLF setting differences on end user machines do not cause the ply submodule repo to appear dirty. Me writing into the source tree then upsets other package managers the maintainers of which raised the issue linked, so the easiest solution for all is for the ply repo to declare its own CRLF policies which are not affected by end user CRLF configuration choices, then all the package managers become happy, and people stop raising issues on my repos :)

Do ask if you need further clarification. I agree, in case you are about to observe this, that it is surprising where open source code ends up going. You only find out when someone complains about something you did or didn't do which is not at all obvious.

**Comment by dabeaz** [comment]
The instructions for PLY clearly state that you should copy it into your project.  Moreover,  I might make incompatible changes to it at any time.   If you want people to stop raising issues on your project, then copy it into your project.
