### ISSUE TITLE
The license copyright line contradicts the BSD 3-clause license below it.

### ISSUE THREAD

**Issue by poikilos** [dabeaz/ply#252]
The phrase "All rights reserved" at the top of the readme and 3 other files is incompatible with the license text following it in the readme. Typically, public licenses are called "some rights reserved" licenses since other people have the right to redistribute the code i.e. part of the license (standard BSD 3-clause) says you don't reserve the right to redistribute entirely to yourself but allow others to do so: "Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer". "All rights reserved" also contradicts the GitHub terms of service, which allows GitHub to redistribute the code of any project on the site in any form and by any means.

I recommend you remove the 3 words "all rights reserved" from all files where it is present, since the BSD license itself (along with the phrase "Copyright (C) 2001-2020 David M. Beazley (Dabeaz LLC)" which fills out the BSD [template](https://opensource.org/licenses/BSD-3-Clause) `Copyright <YEAR> <COPYRIGHT HOLDER>` for the line) is legally valid and has a proven track record, delineating specific rights to the user and to yourself like any other copy of the BSD 3-clause license does:
```
:~/Downloads/git/dabeaz/ply$ grep "rights reserved" -r -n
README.md:5:All rights reserved.
example/cpp/cpp.py:6:# All rights reserved.
ply/lex.py:6:# All rights reserved.
ply/yacc.py:6:# All rights reserved.
```

**Comment by dabeaz** [comment]
Are you a lawyer?

**Comment by poikilos** [comment]
No, I just noticed. It is just an observation and is not meant to be legal advice.

I notice now that some other projects include it, but I'm not sure why the original license wouldn't be enough. Do you know something I don't?

The following projects don't include the phrase:
- [PostgreSQL](https://www.postgresql.org/about/licence/) (BSD/MIT derived custom license)
- [pfSense BSD ports](https://github.com/pfsense/FreeBSD-ports/blob/devel/COPYRIGHT)

The following projects do include the phrase:
- [Panda3D](https://www.panda3d.org/license/)
- [Java 3D Examples](https://github.com/philjord/java3d-examples/blob/master/LICENSE.txt) (engine has different license, but these are the official examples)
- [Flutter](https://github.com/flutter/engine/blob/master/LICENSE)
- [ANTLR](https://www.antlr.org/license.html)
- [WebKit](https://webkit.org/licensing-webkit/) by Apple (dual license GPLv2 & BSD)


Oddly, some of the templates include the phrase (from <https://en.wikipedia.org/wiki/BSD_licenses#4-clause_license_(original_%22BSD_License%22)>):
- 4-clause license (original "BSD License")
- 3-clause license ("BSD License 2.0", "Revised BSD License", "New BSD License", or "Modified BSD License")

and some don't (also from <https://en.wikipedia.org/wiki/BSD_licenses#4-clause_license_(original_%22BSD_License%22)>)
- "Simplified BSD License" or "FreeBSD License"
- BSD Zero Clause License
