### ISSUE TITLE
Regexes are ordered lexicographically

### ISSUE THREAD

**Issue by mwerezak** [dabeaz/ply#254]
The documentation claims that the regex patterns will be placed in the order that methods are added to the lexer object (given to lex()).

However the `linfo.funcsym[state]` list is not in this order. Instead everything appears to be ordered lexicographically, which has been causing a lot of frustration.
https://github.com/dabeaz/ply/blob/master/ply/lex.py#L782

![Screenshot at 2021-05-21 22-56-57](https://user-images.githubusercontent.com/242428/119212743-589dfe80-ba88-11eb-8b81-7c1b70f7bb8c.png)

Why on earth can't it just use the order given in `tokens`?! It's required anyways. Would be explicit and way simpler than trying to puzzle out this magic ordering.

**Comment by mwerezak** [comment]
I hacked a solution it seems to work.

````
    # Build the master regular expressions
    for state in stateinfo:
        func_regex = dict(linfo.funcsym[state])
        simple_regex = dict(linfo.strsym[state])

        ## USE THE ORDER SPECIFIED IN TOKENS
        regex_list = []
        for name in linfo.tokens:
            name = 't_' + name

            f = func_regex.get(name)
            if f is not None:
                regex_list.append('(?P<%s>%s)' % (name, _get_regex(f)))
                if debug:
                    debuglog.info("lex: Adding rule %s -> '%s' (state '%s')", fname, _get_regex(f), state)

            r = simple_regex.get(name)
            if r is not None:
                regex_list.append('(?P<%s>%s)' % (name, r))
                if debug:
                    debuglog.info("lex: Adding rule %s -> '%s' (state '%s')", name, r, state)

        regexs[state] = regex_list
```
Dunno why explicit control over this wasn't something there from the beginning. I can't imagine wanting to build a regex-based tokenizer without being able to control the actual master regex.

**Comment by dabeaz** [comment]
What input are you giving PLY?

**Comment by mwerezak** [comment]
I have a `Lexer` object that contains the `tokens` sequence (a tuple) and bunch of rules as attributes.

The rules are generated from data so they are added after the class is created. All methods are wrapped in `@lex.TOKEN` and assigned to the class.

Inside `Lexer.__init__()` the PLY receives the object instance using `lex.lex(object=self, **kwargs)`

**Comment by dabeaz** [comment]
PLY is a 20 year old tool that works as documented.    If you're doing something else entirely, then you're on your own.  Also, no sample code given.
