### ISSUE TITLE
What types of codes are the PLY suitable for?

### ISSUE THREAD

**Issue by Kaitlyn-lala** [dabeaz/ply#258]
Hello! I wonder what types of codes ( Python, C, Java and so on ) are the PLY suitable for? Thanks!

**Comment by dabeaz** [comment]
You'd use PLY for parsing languages that can be parsed with an LALR(1) parser.   This includes many simple programming languages (C, Go, etc.).  It would probably not include more complex languages like C++ or modern Python.   I'm sorry I can't provide more detail than that, but compiler books would get into more details about the limitations of this parsing algorithm.

**Comment by vpelletier** [comment]
As a more esoteric use, I've used ply to parse USB protocol capture sessions. This of course requires a custom tokeniser, as regexes don't fit for a binary stream, but it works and got me grammar consistency self-checking and protocol error detection for a lot less complexity than if I had to implement them myself with a more traditional protocol dissector.
