### ISSUE TITLE
Allow cloning a parser

### ISSUE THREAD

**Issue by lordmauve** [dabeaz/ply#268]
The LRParser class holds state internal to a parse operation (at least `token`, `symstack` and `statestack`).

This means that it isn't thread-safe (or reentrant).

The Lexer class offers a way around this: the `clone()` method, which I understand is very cheap (compared to copy.deepcopy() or building a lexer from scratch) and means that each tokenisation has independent state.

The LRParser class doesn't have a clone() method. Adding one would mean that a parse operation is threadsafe if you write

```
parser.clone().parse(input, lexer=lexer.clone())
```

**Comment by alexgarel** [comment]
It seems like `parser.parse(input, lexer=lexer.clone())` is already thread safe !

See: https://github.com/jurismarches/luqum/issues/72
