### ISSUE TITLE
raise exception in a p_ function

### ISSUE THREAD

**Issue by hit9** [dabeaz/ply#27]
I am using ply and don't know why `raise SyntaxError` won't run .

But only the `raise` inside `p_error` works. Where am I wrong? Thank you , please attention to this..

**Comment by dabeaz** [comment]
raising a SyntaxError causes an error to be signalled from with a production (which is then caught and handled through normal PLY error recovery).  See http://www.dabeaz.com/ply/ply.html#ply_nn35

**Comment by hit9** [comment]
@dabeaz  thanks, I raised Exception instead of syntaxerror.
