### ISSUE TITLE
Python 3.11: inability to use global inline flags

### ISSUE THREAD

**Issue by RaMdsC** [dabeaz/ply#274]
Python 3.11 includes python/cpython#91222, with the effect that using [global inline flags](https://docs.python.org/3/library/re.html#regular-expression-syntax) `(?aiLmsux)` not at the start of a regular expression results in an error. Before compiling the regexp, ply prepends `(?P<%s>`, where `%s` is the name of the rule, to the regexp of both rules defined by strings https://github.com/dabeaz/ply/blob/ee76ee7c4c0a0f1a53d013a6f0dd124f6a8a20f0/src/ply/lex.py#L639 and rules defined by functions https://github.com/dabeaz/ply/blob/ee76ee7c4c0a0f1a53d013a6f0dd124f6a8a20f0/src/ply/lex.py#L615 With this, rules using regexps with global inline flags result in error. It is possible to pass the flags through `reflags` on call to `lex()` https://github.com/dabeaz/ply/blob/ee76ee7c4c0a0f1a53d013a6f0dd124f6a8a20f0/src/ply/lex.py#L717-L718 But that would apply to all rules in the module, possibly causing undesired behaviour in some of them. As a summary, the introduction of Python 3.11 removes the ability to use per-rule global inline flags.

**Comment by dabeaz** [comment]
Is this a feature request for PLY?

**Comment by RaMdsC** [comment]
The capability "per-rule global inline flags" in PLY is available until Python 3.11.  If support for it was intended in the original design, then this is a bug report. Otherwise, this is a feature request. Thanks.

**Comment by dabeaz** [comment]
This is not something I've ever relied upon or have an idea how to fix.
