### ISSUE TITLE
Read grammar from files

### ISSUE THREAD

**Issue by GNUqb114514** [dabeaz/ply#290]
It looks like your program can only read grammar from the context.
I want to read grammars from lex files. How can I do that?
Or, if it can't now, this will be an enhancement.
Please tell me how to do it, or add it like a feature.

**Comment by dabeaz** [comment]
PLY was developed explicitly with the idea of NOT doing what you describe.  Thus there is no support provided or planned.   You could probably hack it by reading a grammar and turning it into a Python program that uses PLY.  That's really my only advice on it.

**Comment by GNUqb114514** [comment]
OK. I will do that.
