### ISSUE TITLE
License

### ISSUE THREAD

**Issue by m-kuhn** [dabeaz/ply#296]
Hi,

What is the license of ply exactly?
According to the website https://www.dabeaz.com/ply/index.html it is BSD.

Is this correct?
Is it https://opensource.org/license/bsd-3-clause/ ?
Could the text be added as a LICENSE file (similar to other python packages), as this will also allow transporting a license with the blanks in `Copyright <YEAR> <COPYRIGHT HOLDER>` filled in and generally make life easier for packagers.

Thanks :wave:

**Comment by dabeaz** [comment]
The license for PLY is found in its source files.

**Comment by m-kuhn** [comment]
Ah, thanks, that can be copied!

Would you accept a pull request adding a LICENSE file alongside?
