### ISSUE TITLE
"state" is ambiguous in the documentation.

### ISSUE THREAD

**Issue by mrolle45** [dabeaz/ply#297]
Your **`doc/ply.md`** uses the word **"state"** to refer to two different things:
1. Attributes of the `Lexer` object, especially new attributes used in the various methods.
2. Start conditions, given in the `Lexer.states` dict.

I got confused about how the `Lexer` works, until I realized the two different meanings of the word.

I'd suggest that you adopt a different term for at least one of these.  Probably the first meaning, since the `Lexer.states` dict is already part of the public interface.  And whichever you change, be sure that any uses of the name in code comments or non-public interface are changed as well.

**Comment by dabeaz** [comment]
Can you point to a specific paragraph in the docs?
