### ISSUE TITLE
lex.lex() can get some rules in the wrong order.

### ISSUE THREAD

**Issue by mrolle45** [dabeaz/ply#298]
Looking at the code for lex.lex(), I see that if the function is given an actual module or some other instance, then it gets the definitions (of tokens, literals, rules, etc.) by calling dir() of the object.
I think this is wrong, because dir() returns names _in alphabetical order_.  In the case where there is no argument given, it finds the module containing the caller and uses that module's global variables; these are sorted in the order in which they were defined.

I say that dir() is wrong because the regular expressions for the possible token types are tried in this order (for those that are defined by functions).  If lex() gets them out of order, it might match the wrong token type.  For example, if your module has
```
def t_HASH(t):
    r'#'
    return t
def t_HASHHASH(t):
    r'##'
    return t
```
then an input of `##` would be tokenized as two `#` tokens, not a single `##` token.

I would suggest that instead of dir(x) you use x.__dict__.

**Comment by dabeaz** [comment]
PLY performs its own sorting of the definitions, the rules for which are described in the docs.  Also, PLY predates Python's change to preserving dictionary order by more than 15 years.    Directly accessing the dictionary doesn't work with inheritance.
