### ISSUE TITLE
Ply keeps regenerating parsetab.py even though nothing has changed

### ISSUE THREAD

**Issue by jpakkane** [dabeaz/ply#31]
Create a file plytest.py with the following contents:

```
#!/usr/bin/python3 -tt

import ply.lex as lex
import ply.yacc as yacc

tokens = ['NAME']

t_NAME='[a-zA-Z]+'

def p_word(t):
    'word : NAME'
    t[0] = t[1]

lex.lex()
parser = yacc.yacc()
result = parser.parse('abcd')
```

Then do this:

mkdir subdir; cd subdir
../plytest.py

Ply will generate parsetab.py in the subdir. But if you run plytest.py again, it will regenerate parsetab.py and overwrite the old one. The produced files are always different. A sample diff between two runs looks like this.

    < _lr_action_items = {'NAME':([0,],[1,]),'$end':([1,2,],[-1,0,]),}
    ---
    > _lr_action_items = {'$end':([1,2,],[-1,0,]),'NAME':([0,],[1,]),}

The same happens when you try to write output in a different directory with yacc.yacc(outputdir='some_dir').

If you run the script with ./plytest.py it will work.

**Comment by dabeaz** [comment]
Have incorporated some changes to make this more reliable in PLY-3.5.  Includes narrowing the import statement to just consider the outputdir setting (noted above) and some changes in the signature calculation to make sure it is compatible with both Python 2 and 3.

**Comment by nnen** [comment]
The issue has not been fixed in any way in PLY-3.7 on Python 3.5.1.

**Comment by dabeaz** [comment]
Check to make sure there's not another parsetab.py that's being imported from a different directory than the one PLY is using.

**Comment by boriel** [comment]
I'm still experiencing this issue (ZX Basic compiler) in python 3.6.1
In python 2.7.12 work as expected.

Strangely, it only happens to one of the 3 parsers (zxb.py)
https://bitbucket.org/boriel/zxbasic/branch/py2to3

**Comment by boriel** [comment]
Okay, it seems to be an issue with py3 and hashing functions, always returning the element of in different order from some collections. Concretely, the tokens from the lexer always in sort of random order, thus generating a different signature each time. In python2 this issue does not occur.

Here is the fix (just a single line)
https://github.com/boriel/ply/commits/Ply_keeps_regenerating_parsetab.py_even_though_nothing_has_changed_

I can pull request across forks, but it's just a single line.
Tested under python 2.7.12+ and python 3.5.1+

**Comment by PiJoules** [comment]
Hey @dabeaz , just wanted to know when you will be pushing the next version of ply that contains this update?

It took me a while to figure out this was the reason why my parsetab.py kept being generated. I had a dict of reserved words whose keys I just added to my tokens and didn't realize the signature depended on the order of the tokens.

This isn't on the latest PyPi package or github release and I think it would save time for others who use a lot of reserved words from having to track this.
