### ISSUE TITLE
Install/deployment methodology best practices

### ISSUE THREAD

**Issue by dbc** [dabeaz/ply#38]
I am struggling with how best to write a setup.py to deploy a tool built using ply.  The problem is how to deal with the parser output files.  The fact that my tool uses ply under the hood should be transparent to the user, so I want to avoid leaving ply-dust all over the user's workspace.

In principal, it is simple enough to simply call my tool once at the end of the install script to generate the parse tables.  The question is, where should they go? It would be nice to let them land in the package directory along with other support modules, but that directory name needs to somehow get permanently patched into the executable.

My grammar is small enough that I could simply turn-off caching, but I still get the parser.out file, even with debug=0, and a message about "Generating LALR tables."
edit: OK, so that was a PEBKAC, I was confused about debug=0 during generation versus usage.  With debug=0 during generation, the output and the "Generating..." message can be suppressed. Still, this is only a solution for small grammars.

A third approach may be to create the parse tables in $HOME/.foo but that has it's own issues of making sure the path exists, etc.

What are best practices for deploying ply?

---

Edit #2 -- Well, I have what seems like a solution, but I'd like feedback -- it seems very warty.
- Added a --runonceoninstall option to my application.
- setpy.py does `subprocess.call(''mytool','--runonceoninstall'])` at the end
- my parsing module does
  
  _cacheDir = dirname(__file__) # Find out where this module lives during install.
  
  _parser = yacc.yacc(debug=0,outputdir=_cacheDir) # Cache files to install directory.
- my main driver causes my parser to get imported, which triggers the yacc.yacc() call above
- the --runonceoninstall option does `import parsetab` which causes the creation of parsetab.pyc

This appears to work, but seems crufty.  Suggestions welcome.

**Comment by johnyf** [comment]
A top-down approach is simpler, and so more robust. An example `setup.py` can be found in [`astutils`](https://github.com/johnyf/astutils/blob/master/examples/setup.py). It uses `pip` to install `ply` first. It then builds the tables *before* copying to `site-packages`. Note that it reasons only about relative paths, locally, and does not have to do any fragile path manipulation or any assumptions. During installation, write access rights exist for wherever `pip` downloads, and for writing to `site-packages`.

This approach works with both `pip install`, as well as `python setup.py install`, and `python setup.py develop`. It leaves it to `python` to just copy all the modules to `site-packages` (or leave them there, in case of `develop`). Also, it is the same for development, installation from an index or source, with `git` present or absent. This automates things, requiring no manual changes.

An alternative approach can be found in [`pycparser`](https://github.com/eliben/pycparser/blob/master/setup.py#L12). It adds a post-`install` and post-`sdist` task to `setuptools.setup` using `cmdclass`. The task generates the tables *inside* `site-packages`. This approach is more involved and touches the internals of `setuptools`, thus less robust. [PEP 20](https://www.python.org/dev/peps/pep-0020/)-wise it is nested.
