### ISSUE TITLE
token lineno lost on error recovery

### ISSUE THREAD

**Issue by dbc** [dabeaz/ply#39]
In a grammar where NL is the token returned by newline characters, and SOME_KW is a keyword, I have some recovery rules of the form:

``widget : SOME_KW error NL``

Which, after accepting SOME_KW and encountering a syntax error, consumes tokens up to NL.  So far, so good.  However, the action:

``errorAtLine = p.lineno(1)``

returns None instead of the line number associated with SOME_KW -- the line number appears to get lost during error recovery, but it is there on successful actions.  This leads me to believe error recovery is wiping it out. For my current purpose, I am using  ``p.lineno(3)`` as a work-around for picking up a line number near the syntax error.

Sorry, no test case right now... I'll try to make a cut down test case in the near future.

**Comment by dabeaz** [comment]
Not able to reproduce this in the current version, but will continue to investigate.

**Comment by dabeaz** [comment]
It's possible that the error token won't have lineno information on it if line-number tracking is disabled.  Make sure parse(tracking=True) is used to enable tracking of position information on non-terminals.
