### ISSUE TITLE
call_errorfunc() should return the result of errorfunc()

### ISSUE THREAD

**Issue by lelit** [dabeaz/ply#44]
I added the following note to the [commit](https://github.com/dabeaz/ply/commit/c0f9ed554f3425b08b717933f94eb34485e8c993) that (I think) introduced the problem:

Shouldn't the call_errorfunc() actually return the result of errorfunc() [here](https://github.com/dabeaz/ply/blob/master/ply/yacc.py#L203)?
Otherwise the logic in the parse() methods (currently at [line 566](https://github.com/dabeaz/ply/blob/master/ply/yacc.py#L566), [line 844](https://github.com/dabeaz/ply/blob/master/ply/yacc.py#L844) and [line 1105](https://github.com/dabeaz/ply/blob/master/ply/yacc.py#L1105)) won't ever see the fixup token.

**Comment by dabeaz** [comment]
Fixed in PLY 3.5.

**Comment by lelit** [comment]
Thank you, I will try it out, even if I do not recognize any related fix in the mentioned `call_errorfunc()`...
