### ISSUE TITLE
Test errors and failures with Python <2.6, Python ≥3.5, Jython and PyPy

### ISSUE THREAD

**Issue by Arfrever** [dabeaz/ply#50]
Test suite of PLY has some errors and failures with Python &lt;2.6, Python &ge;3.5, Jython and PyPy.
All results for PLY trunk.

**Comment by dabeaz** [comment]
Fixed for Python > 2.6.   Won't fix test failures for Python 2.5

**Comment by Arfrever** [comment]
I have no need for Python <2.6.
Please update `README.md`, which currently contains:
```
Requirements
============
PLY requires the use of Python 2.2 or greater.
```

**Comment by Arfrever** [comment]
And doc/ply.html:
```
Although PLY
works with versions as far back as Python 2.2, some of its optional features
require more modern library modules.
```
