### ISSUE TITLE
lexer.input() does not reset the state stack

### ISSUE THREAD

**Issue by bazsi** [dabeaz/ply#56]
If a lexer is using push_state() / pop_state(), that stack is not erased when a new input is specified via the input() method.

```
    def input(self,s):
        # Pull off the first character to see if s looks like a string
        c = s[:1]
        if not isinstance(c,StringTypes):
            raise ValueError("Expected a string")
        self.lexdata = s
        self.lexpos = 0
        self.lexlen = len(s)
```

In fact, it is pretty difficult to unwind it without accessing lex internals, so I have something like this in my code for now:

```
        if hasattr(self._lexer, "lexstatestack"):
            while len(self._lexer.lexstatestack) > 0:
                self._lexer.pop_state()
```

**Comment by dabeaz** [comment]
Traditionally, specifying new input has never reset anything in the lexer.  This is to support use cases where input might be assembled in chunks or from different sources, but made to appear as if it were a continuous source of tokens to the parser.   Honestly, I'm not sure how well this is defined though.  So, would need to look at it further.

**Comment by vpelletier** [comment]
> This is to support use cases where input might be assembled in chunks or from different sources

How would this work at `yacc.LRParser` level ? As far as I can see, current API will loop until `get_token` returns a false value (ie, `None`), at which point it will insert a `$end` token.

Background: I tried to use ply to represent the grammar of a protocol, which my program analyses as the protocol is being used between two independent entities. So my lexer is very custom. As I want parser's output to be updated as soon as possible after link activity, I want to push tokens as soon as they are received - without checking if they make the grammar reach topmost rule (where no state is lost if `$end` is encountered) as this would defeat the purpose of using ply automated state machine generation. So far, the only solution I found was to [extend `yacc.LRParser`](https://github.com/vpelletier/ITI1480A-linux/blob/master/iti1480a/incremental_yacc.py) so as to reuse its internals - so I would be very interested to know of a better way if it exists.

**Comment by bazsi** [comment]
Well, supporting the use case you are describing (supply input in multiple chunks) would be pretty useful, and is possible with traditional bison/flex. 

However when I opened this ticket I came to the conclusion that this was not supported (I cant remember the exact details but for sure I read the source), thats why I asked.

Anyway, my code now reuses the parser instance and calls input, but I could instantiate a new parser instead.

So on my part, input() which allows multiple chunks would be the best option.

**Comment by dabeaz** [comment]
An incremental lexer would require passing a modified lexer and/or tokenfunc to the parser.  For example:

    def modified_get_token():
          # Return the next token
          ...
          return tok

    yacc.parse(tokenfunc=modified_get_token)

Within the modified_get_token() function, you could drive the lexer, check for EOF, and feed input in a more customized manner.  

Again, I don't know if this has ever been fully explored in PLY.  Maybe needs some more documentation.  I will look into this.

**Comment by dabeaz** [comment]
For now, I'm going to leave the parsing state alone on new input.   The lexer() can have its state manually reset on new input if needed.   There are more advanced uses where you would not want to reset the state on input.
