### ISSUE TITLE
error in validate_file 

### ISSUE THREAD

**Issue by bdcht** [dabeaz/ply#6]
When a lexer is build from a class instance (like in §4.14 of the documentation), the LexerReflect object will call its validate_rules() method (by default optimize=0), which calls ultimately validate_file(f) on each file.

validate_file, checks for redefinition of rule functions by parsing the entire python file...but it should restrict itself to the class namespace. This leads to incorrect errors when several classes (with possibly the same set of rules 't_xxx') are defined within the same python file (see example below).

Fix: I'd suggest to get rid of validate_file anyway which seems a bit odd.

example : plytest.py------------------------------------------

from ply import lex

class lexer1(object):
    def __init__(self):
        self.tokens = ('regulars',)
        self.t_ignore = ' '
    def t_regulars(self,t):
        r'\w+'
        return t
    def t_ANY_error(self,t):
        print "Illegal character '%s'" % t.value[0]
        t.lexer.skip(1)
    def build(self,**kargs):
        self._lexer = lex.lex(module=self,**kargs)
    def test(self,data):
        self._lexer.input(data)
        while 1:
            tok = self._lexer.token()
            if not tok: break
            print tok

class lexer2(object):
    def __init__(self):
        self.tokens = ('regulars',)
        self.t_ignore = ' '
    def t_regulars(self,t):
        r'[0-9]+'
        return t
    def t_ANY_error(self,t):
        print "Illegal character '%s'" % t.value[0]
        t.lexer.skip(1)
    def build(self,**kargs):
        self._lexer = lex.lex(module=self,**kargs)
    def test(self,data):
        self._lexer.input(data)
        while 1:
            tok = self._lexer.token()
            if not tok: break
            print tok

l1 = lexer1()
l2 = lexer2()

l1.build()
-----------------------------------------------------------------

**Comment by dabeaz** [comment]
Have revisited the code for this.   Error reporting is an important part of PLY that I don't want to remove.  However, changing the error checking code to understand different contexts such as classes and functions (closures) is going to be difficult and error-prone.   I don't think it's unreasonable to require lexers/parsers to be defined in separate source files.   

I'm going to close this, but I'm going to make a comment in the documentation related to this.
