### ISSUE TITLE
Partial ES6 Transpiler

### ISSUE THREAD

**Issue by joeedh** [dabeaz/ply#62]
Hi all.  I wrote [a ES6 transpiler](https://github.com/joeedh/fairmotion/tree/master/tools/extjs_cc) using PLY, which I've been using in production code for several years now.  I'm planning on switching to a different transpiler (so I don't have to continue maintaining my own), but I wanted to let the PLY developers know I really love PLY and express my deepest gratitude.  I even implemented it's lexical scanner API [in JavaScript](https://github.com/joeedh/STRUCT/blob/master/src/struct_parseutil.js).

PLY was my first experience with bottom-up compiler-compilers.  I found the tutorial on the website extremely helpful.  At the time, I had found myself suddenly in need of an ES6 transpiler.  I panickly searched the web, only to discover (it's funny, but true) that every single transpiler website was down that day, which made me (erroneously) think they were not being maintained.

That was when I turned to PLY.  I managed to get something that served my basic needs up and running in, if memory serves, two weeks or so.  The sheer speed I could work in PLY was awe-inspiring.  Of course I ran into difficult grammar issues like everyone else, though it helped that the ES6 spec had plenty of tips on making JavaScript's weird grammar work in a bottom-up parser.

Anyway, my actual transpiler code (especially the AST manipulation stuff) is horrible, but I thought you might want to know that someone found your project (quite) useful.

**Comment by dabeaz** [comment]
Glad to hear that PLY was useful!
