### ISSUE TITLE
Reduce conflicts on generated yacctab.py

### ISSUE THREAD

**Issue by lelit** [dabeaz/ply#64]
I notice that the latest version of ply (actually, current master), puts the fullpath of the yacctab.py in its header, something it didn't do in previous versions, and does not with lextab.py.

Consider:

```diff
--- a/src/slimit/yacctab.py
+++ b/src/slimit/yacctab.py
@@ -1,330 +1,330 @@
 
-# yacctab.py
+# /home/lele/wip/slimit/src/slimit/yacctab.py
 # This file is automatically generated. Do not edit.
-_tabversion = '3.2'
+_tabversion = '3.5'
```

This may introduce noisy/spurious conflicts when two different people rebuild the file.

As a side note, maybe it would be nicer having similar headers in the generated files: the `lextab.py` one is like the following:

```
# lextab.py. This file automatically created by PLY (version 3.6). Don't edit!
_tabversion   = '3.5'
```

**Comment by dabeaz** [comment]
Fixed the filename issue.

**Comment by johnyf** [comment]
Relevant also to #58.
