### ISSUE TITLE
lexer interface specification?

### ISSUE THREAD

**Issue by jason-s** [dabeaz/ply#69]
Is there a description of the lexer interface required by the PLY parser? I am interested in combining the PLY parser layer with the [`vera++` tool](https://bitbucket.org/verateam/vera/wiki/Home) (which already has a tokenizer) and am wondering what methods/properties I need to provide so that PLY's parser could use a "foreign" lexer.

**Comment by johnyf** [comment]
This is noted [in the docs](http://www.dabeaz.com/ply/ply.html) under “4.20 Miscellaneous Issues”:

---
 If you are going to create a hand-written lexer and you plan to use it with `yacc.py`, it only needs to conform to the following requirements:

- It must provide a token() method that returns the next token or None if no more tokens are available.
- The `token()` method must return an object `tok` that has type and value attributes. If line number tracking is being used, then the token should also define a `lineno` attribute. 

---

**Comment by jason-s** [comment]
ah -- cool, thanks.
