### ISSUE TITLE
Lexer lextokens changed from dict to set, breaks oe-lite

### ISSUE THREAD

**Issue by kimrhh** [dabeaz/ply#75]
Hi,

With the release of ply-3.6 we have run into an issue when using it in the OE-lite project. See this issue: https://github.com/oe-lite/core/issues/27

Basically, the lextoken was changed from a dict to a set (although the comment in the code still says dict ;) ), which breaks our code.

I'm thinking we are likely using some internal that we should not mess with as a consumer of Ply, however we need some way of accessing this information to make it work for OE-lite. We can of course just work around it, converting either a set or a dict to the list of tokens we need, but I would like to ask for your opinion about it to make a better solution possible.

Br,
Kim

**Comment by dabeaz** [comment]
This is being caused because someone used a "work in progress" version of PLY and is shipping incompatible lextab.py and parsetab.py files.   The solution is to remove those files and to rerun PLY.
