### ISSUE TITLE
Decorating production definition functions.

### ISSUE THREAD

**Issue by bionikspoon** [dabeaz/ply#86]
### Summary

Using decorators on yacc functions, totally breaks everything.

```python
@type_check
def p_expression_plus(p):
    'expression : expression PLUS term'
    p[0] = p[1] + p[3]
```

My use case for decorators: I'm struggling with rules and want to add a type checking decorator, to limit the possible number of problems--particularly while debugging.

---

### Cause

I've tracked the problem down to one line of code: [yacc.py#L3110](https://github.com/dabeaz/ply/blob/master/ply/yacc.py#L3110) 

```python
line = item.__code__.co_firstlineno
```

This line number is used to set precedence level of grammar rules.  Unfortunately, it points to the decorator instead of the function.  And worse, `__code__` and all of it's attributes are read-only.

---

### A solution

I'll put in a PR for A solution. I suspect there's a more elegant solution, but it's a solution nonetheless.   

My solution is to manually add that line number to an attribute on the wrapping function, and then  `yacc` checks for that attribute before setting the line number.

An example of manually setting the attribute:

```python
from functools import wraps

def type_check(func):
    @wraps(func)
    def wrapper(p):
        func(p)
        #  if p[0] not int ... raise error ...
    wrapper.co_firstlineno = func.__code__.co_firstlineno
    return wrapper
```

Then that one line in the `yacc` library simply becomes: 

```python
line = getattr(item, 'co_firstlineno', item.__code__.co_firstlineno)
```

and everything else works!

---

### A theoretically better solution

A potentially more elegant solution might use something like the `__wrapped__` attribute or a comparable introspection.  I don't know what's available for python 2.

---
edit: ref #87

**Comment by dabeaz** [comment]
A weird issue here to be sure.  Incorporated the pull request with a patch.
