### ISSUE TITLE
Ply can crash if SyntaxError is raised inside a production

### ISSUE THREAD

**Issue by pjbaker** [dabeaz/ply#93]
According to the documentation, production rules can signal errors by raising the `SyntaxError` exception. However when I try this, my program crashes due to an IndexError exception inside Ply.

A simple example:

    import ply.lex as lex
    import ply.yacc as yacc
    
    tokens = ('A', 'B')
    
    t_A = 'a'
    t_B = 'b'
    
    t_ignore = ' \t'
    
    def t_error(t):
        print("Illegal character '%s'" % t.value[0])
        t.lexer.skip(1)
    
    lexer = lex.lex()
    
    def p_foo(p):
        """foo : A B"""
        raise SyntaxError()
    
    def p_error(p):
        print("Syntax error in input!")
    
    parser = yacc.yacc()
    
    print(parser.parse('a b'))

The result of running this code is:

    Generating LALR tables
    Traceback (most recent call last):
      File "PlyTest3.py", line 26, in <module>
        print(parser.parse('a b'))
      File "<...>\ply\yacc.py", line 331, in parse
        return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
      File "<...>\ply\yacc.py", line 1115, in parseopt_notrack
        state = statestack[-1]
    IndexError: list index out of range

Should I be doing something differently when raising an error?

**Comment by dabeaz** [comment]
Fixed (I hope).
