### ISSUE TITLE
Module version 3.7 --> 3.8

### ISSUE THREAD

**Issue by hsucw** [dabeaz/ply#94]
I want to check which version I installed.

`pip install ply==3.8`

then
`import ply`
` ply.__version__`
`'3.7'`

I checked the source code,
the __init__.py should be correct as 

`- __version__ = '3.7'`
`+ __version__ = '3.8'`

**Comment by popizdeh** [comment]
ANNOUNCE file says PLY-3.7 in few places.

**Comment by dabeaz** [comment]
Fixed.
