### ISSUE TITLE
Undesirable creation of lextab.py file

### ISSUE THREAD

**Issue by theres-waldo** [dabeaz/ply#96]
Hi there!

I work on Mozilla Firefox, and I'm finding that while running certain automated tests, a "lextab.py" file is created in Firefox's source directory.

I have traced the creation of this file to the PLY package, with the following backtrace:

```

  /home/botond/dev/mozilla/central/mach(148)<module>()
-> main(sys.argv[1:])
  /home/botond/dev/mozilla/central/mach(80)main()
-> sys.exit(mach.run(args))
  /home/botond/dev/mozilla/central/python/mach/mach/main.py(343)run()
-> return self._run(argv)
  /home/botond/dev/mozilla/central/python/mach/mach/main.py(440)_run()
-> debug_command=args.debug_command, **vars(args.command_args))
  /home/botond/dev/mozilla/central/python/mach/mach/registrar.py(90)_run_command_handler()
-> result = fn(**kwargs)
  /home/botond/dev/mozilla/central/layout/tools/reftest/mach_commands.py(323)run_reftest()
-> return self._run_reftest(**kwargs)
  /home/botond/dev/mozilla/central/layout/tools/reftest/mach_commands.py(371)_run_reftest()
-> return reftest.run_desktop_test(**kwargs)
  /home/botond/dev/mozilla/central/layout/tools/reftest/mach_commands.py(180)run_desktop_test()
-> import runreftest
  /home/botond/dev/mozilla/central/build/mach_bootstrap.py(445)__call__()
-> module = self._original_import(name, globals, locals, fromlist, level)
  /home/botond/dev/mozilla/central/layout/tools/reftest/runreftest.py(38)<module>()
-> from marionette import Marionette
  /home/botond/dev/mozilla/central/build/mach_bootstrap.py(445)__call__()
-> module = self._original_import(name, globals, locals, fromlist, level)
  /home/botond/dev/mozilla/central/testing/marionette/harness/marionette/__init__.py(17)<module>()
-> from .runner import (
  /home/botond/dev/mozilla/central/build/mach_bootstrap.py(445)__call__()
-> module = self._original_import(name, globals, locals, fromlist, level)
  /home/botond/dev/mozilla/central/testing/marionette/harness/marionette/runner/__init__.py(17)<module>()
-> from .mixins import (
  /home/botond/dev/mozilla/central/build/mach_bootstrap.py(445)__call__()
-> module = self._original_import(name, globals, locals, fromlist, level)
  /home/botond/dev/mozilla/central/testing/marionette/harness/marionette/runner/mixins/__init__.py(17)<module>()
-> from .browsermob import (
  /home/botond/dev/mozilla/central/build/mach_bootstrap.py(445)__call__()
-> module = self._original_import(name, globals, locals, fromlist, level)
  /home/botond/dev/mozilla/central/testing/marionette/harness/marionette/runner/mixins/browsermob.py(7)<module>()
-> from browsermobproxy import Server
  /home/botond/dev/mozilla/central/build/mach_bootstrap.py(445)__call__()
-> module = self._original_import(name, globals, locals, fromlist, level)
  /home/botond/dev/mozilla/central/testing/marionette/harness/marionette/runner/mixins/browsermob-proxy-py/browsermobproxy/__init__.py(3)<module>()
-> from .server import Server
  /home/botond/dev/mozilla/central/build/mach_bootstrap.py(445)__call__()
-> module = self._original_import(name, globals, locals, fromlist, level)
  /home/botond/dev/mozilla/central/testing/marionette/harness/marionette/runner/mixins/browsermob-proxy-py/browsermobproxy/server.py(7)<module>()
-> from .client import Client
  /home/botond/dev/mozilla/central/build/mach_bootstrap.py(445)__call__()
-> module = self._original_import(name, globals, locals, fromlist, level)
  /home/botond/dev/mozilla/central/testing/marionette/harness/marionette/runner/mixins/browsermob-proxy-py/browsermobproxy/client.py(1)<module>()
-> import requests
  /home/botond/dev/mozilla/central/build/mach_bootstrap.py(445)__call__()
-> module = self._original_import(name, globals, locals, fromlist, level)
  /home/botond/dev/mozilla/central/python/requests/requests/__init__.py(53)<module>()
-> from .packages.urllib3.contrib import pyopenssl
  /home/botond/dev/mozilla/central/build/mach_bootstrap.py(445)__call__()
-> module = self._original_import(name, globals, locals, fromlist, level)
  /home/botond/dev/mozilla/central/python/requests/requests/packages/urllib3/contrib/pyopenssl.py(55)<module>()
-> import OpenSSL.SSL
  /home/botond/dev/mozilla/central/build/mach_bootstrap.py(445)__call__()
-> module = self._original_import(name, globals, locals, fromlist, level)
  /usr/lib/python2.7/dist-packages/OpenSSL/__init__.py(8)<module>()
-> from OpenSSL import rand, crypto, SSL
  /home/botond/dev/mozilla/central/build/mach_bootstrap.py(445)__call__()
-> module = self._original_import(name, globals, locals, fromlist, level)
  /usr/lib/python2.7/dist-packages/OpenSSL/rand.py(11)<module>()
-> from OpenSSL._util import (
  /home/botond/dev/mozilla/central/build/mach_bootstrap.py(445)__call__()
-> module = self._original_import(name, globals, locals, fromlist, level)
  /usr/lib/python2.7/dist-packages/OpenSSL/_util.py(4)<module>()
-> binding = Binding()
  /usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py(89)__init__()
-> self._ensure_ffi_initialized()
  /usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py(113)_ensure_ffi_initialized()
-> libraries=libraries,
  /usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/utils.py(57)build_ffi()
-> ffi.cdef("\n".join(cdef_sources))
  /usr/lib/python2.7/dist-packages/cffi/api.py(103)cdef()
-> self._parser.parse(csource, override=override, packed=packed)
  /usr/lib/python2.7/dist-packages/cffi/cparser.py(166)parse()
-> self._internal_parse(csource)
  /usr/lib/python2.7/dist-packages/cffi/cparser.py(172)_internal_parse()
-> ast, macros, csource = self._parse(csource)
  /usr/lib/python2.7/dist-packages/cffi/cparser.py(127)_parse()
-> ast = _get_parser().parse(csource)
  /usr/lib/python2.7/dist-packages/cffi/cparser.py(32)_get_parser()
-> _parser_cache = pycparser.CParser()
  /usr/lib/python2.7/dist-packages/pycparser/c_parser.py(76)__init__()
-> lextab=lextab)
  /usr/lib/python2.7/dist-packages/pycparser/c_lexer.py(66)build()
-> self.lexer = lex.lex(object=self, **kwargs)
  /home/botond/dev/mozilla/central/other-licenses/ply/ply/lex.py(1004)lex()
-> lexobj.writetab(lextab,outputdir)
> /home/botond/dev/mozilla/central/other-licenses/ply/ply/lex.py(177)writetab()
-> tf.write("# %s.py. This file automatically created by PLY (version %s). Don't edit!\n" % (tabfile,__version__))

```

I realize the creation of this file is probably not a bug in PLY; I was just hoping that I could get some guidance from the developers of PLY that would help me determine which component of the stack to blame for its creation in the source directory.

Specifically, I would be interested to know:
- What is the purpose of this file
- What options does PLY provide for controlling whether and where to create this file

Thanks in advance!

**Comment by johnyf** [comment]
The `lextab.py` file is the table generated for the lexer of the parser.
From the trace provided, it appears that [`pycparser`](https://github.com/eliben/pycparser), a parser for the C language, is producing this table, in particular [its lexer](https://github.com/eliben/pycparser/blob/a47b919287a33dea55cc02b2f8c5f4be2ee8613c/pycparser/c_lexer.py#L66).
[`_build_tables`](https://github.com/eliben/pycparser/blob/a47b919287a33dea55cc02b2f8c5f4be2ee8613c/pycparser/_build_tables.py) is another file relevant to dumping parser tables.

The `lextab.py` table file is generated as an optimization, and to avoid issues when running in Python's optimized mode. The lexer from it next time the Python module is used, instead of regenerating the lexer (and parser -- placed in another file, ending by default in `parsetab`) on every invocation, which can be expensive for real languages like C.

This is documented in [4.13 Optimized mode](http://www.dabeaz.com/ply/ply.html#ply_nn15).
About disabling parser tables too, [6.12 Miscellaneous Yacc Notes](http://www.dabeaz.com/ply/ply.html#ply_nn36) could also be useful. See also [this discussion](http://stackoverflow.com/questions/12644902/how-to-prevent-table-regeneration-in-ply). An example skeleton for a lexer and parser can be found [here](https://github.com/johnyf/astutils/blob/master/astutils/ply.py).

It seems that, in order to disable generation of the table file, you may have to change `pycparser`'s behavior, though I'm not familiar with whether it provides any options for disabling it using its API (likely that it does).

**Comment by theres-waldo** [comment]
> It seems that, in order to disable generation of the table file, you may have to change pycparser's behavior, though I'm not familiar with whether it provides any options for disabling it using its API (likely that it does).

I am OK with creating the file if it improves performance, but it should be created in the build directory rather than the source directory. Can the directory where the file is created be controlled (at the level of PLY's API), or is it tied to the current working directory or something like that?

**Comment by johnyf** [comment]
Looking at the code of the function `ply.lex.lex`, the [argument `outputdir`](https://github.com/dabeaz/ply/blob/b1228ee07d064787acbdca61238b17710c13fbd8/ply/lex.py#L861) controls the directory where the lexer table file [is written](https://github.com/dabeaz/ply/blob/b1228ee07d064787acbdca61238b17710c13fbd8/ply/lex.py#L1040), and [`lextab`](https://github.com/dabeaz/ply/blob/b1228ee07d064787acbdca61238b17710c13fbd8/ply/lex.py#L860) the name of that file.

**Comment by arcolife** [comment]
facing a similar situation:

```
WARNING: (<class 'pycparser.ply.yacc.VersionError'>, VersionError('yacc table file version is out of date',), <traceback object at 0x7f99058e1488>)
```

generates both yacctab.py
```
# yacctab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'
....
```

and lextab.py

```
# pycparser.lextab.py. This file automatically created by PLY (version 3.4). Don't edit!
_tabversion   = '3.4'
```
it tends to display the same warning everytime, even though it had generated those files (in the sourcedir). 

Any movement on this?

**Comment by dabeaz** [comment]
This problem is almost caused by a preexisting table file that's being imported elsewhere on the Python path or a file that can't be overwritten due to some kind of permission/access issue.

**Comment by arcolife** [comment]
I tried running this as root and without. And reinstalled all deps locally and in root, separately, each time. And throughout those iterations, I ran the same script both root / non-root user, but still got the error each time.

**Comment by dabeaz** [comment]
If PLY is constantly regenerating files, it means that it's picking up an import of the file 'lextab.py' or 'parsetab.py' from some other location.   Suggest interactive debugging::

      >>> import lextab
      >>> lextab.__file__
      (look at output)

**Comment by dabeaz** [comment]
Closing this for now.  Not sure there was a resolution, but regeneration of files is almost caused by a stale file appearing somewhere or some other issue with the file system (e.g., lack of permissions).
