### ISSUE TITLE
with version 3.8 the lexer fails when the lexer specification is read from a .pyc file without the .py source present

### ISSUE THREAD

**Issue by vineet7kumar** [dabeaz/ply#97]
In a case (usually in a closed source environment) if the module containing the lexer specification is present as .pyc file and the corresponding .py source does not exist, the lexer fails with the following error:
 ```
File "C:\Users\admin\Anaconda2\lib\site-packages\ply\lex.py", line 906, in lex

    if linfo.validate_all():
  File "C:\Users\admin\Anaconda2\lib\site-packages\ply\lex.py", line 580, in validate_all
    self.validate_rules()
  File "C:\Users\admin\Anaconda2\lib\site-packages\ply\lex.py", line 822, in validate_rules
    self.validate_module(module)
  File "C:\Users\admin\Anaconda2\lib\site-packages\ply\lex.py", line 833, in validate_module
    lines, linen = inspect.getsourcelines(module)
  File "C:\Users\admin\Anaconda2\lib\inspect.py", line 690, in getsourcelines
    lines, lnum = findsource(object)
  File "C:\Users\admin\Anaconda2\lib\inspect.py", line 529, in findsource
    raise IOError('source code not available')
IOError: source code not available
```

This error is caused because in version 3.8 `validate_module()` method uses the inspect module to get the source of the module in which the lexer rules are defined. 

If `validate_module()` cannot find the source, it should simply return without throwing an error. If the .pyc file is present without the .py file, that would probably be because the system is tested and is in production. If none of the .py and .pyc are present, it should fail anyways.
Note that in version 3.4, the corresponding validation was done by `validate_file()` method which tried to read the source .py file as a test file and returned without throwing an exception if the .py file was not present.

Moreover, even if the .py file is present in production environment, using inspect by default means that the source code for token definitions is validated every time the lexer is built. Is there a reason why this is done? It seems to be unnecessary once the code has been developed and tested. Is there an option to turn `validate_module()` on only for the dev/debug environment?

I am willing to make the required changes.

Thanks.

**Comment by dabeaz** [comment]
Fixed.
